### ISSUE TITLE
Build succeeded : TIC-80 for Raspberry Pi (Raspbian Buster)

### ISSUE THREAD

**Issue by kikeroga3** [nesbox/TIC-80#1017]
sudo apt update
sudo apt dist-upgrade

sudo apt install --reinstall libraspberrypi0 libraspberrypi-dev libraspberrypi-bin
sudo apt install build-essential libgtk-3-dev libsdl2-dev zlib1g-dev liblua5.3-dev libgif-dev
sudo apt install git cmake
sudo apt install raspberrypi-kernel-headers

sudo cp /opt/vc/lib/libbcm_host.so /usr/local/lib

git clone --recursive https://github.com/nesbox/TIC-80
cd TIC-80/build
cmake ..
make

**Comment by nesbox** [comment]
Awesome, maybe add it to the Build Instructions?
Thank you :)

**Comment by kikeroga3** [comment]
I hope this will help :)

**Comment by kikeroga3** [comment]
Defect report

1. TIC-80 Start (window mode)
<img src="https://user-images.githubusercontent.com/24917310/76856125-f51dad00-6895-11ea-95d3-ee8cfe8ae10a.jpg" width="45%" height="45%">

2. Press F11 (fullscreen)
<img src="https://user-images.githubusercontent.com/24917310/76856129-f6e77080-6895-11ea-8f40-f08154dd921f.jpg" width="45%" height="45%">

3. Press F11 again (window mode)
<img src="https://user-images.githubusercontent.com/24917310/76856134-f8189d80-6895-11ea-80a3-8b83d7cd9e5c.jpg" width="45%" height="45%">

Returning to window mode from fullscreen will make the screen smaller than before.
There is no problem in operation.

TIC-80 version 0.80.1055-dev

**Comment by nesbox** [comment]
Added cross-compilation to Raspberry PI to Github Actions here ee40393 20ff233.

**Comment by ricolaoz** [comment]
Hello,
after several unsuccessful attempts, here is the return of the command : cmake .. -DBUILD_PRO=On (same thing with just "cmake ..")
`Sur la branche master
Votre branche est à jour avec 'origin/master'.

rien à valider, la copie de travail est propre
Building for target : Linux
PROJECT_VERSION: 0.90.1533-dev
BUILD_SDLGPU: OFF
BUILD_TOUCH_INPUT: OFF
CMake Warning (dev) at vendor/sdl2/CMakeLists.txt:6 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'jack'
--   No package 'jack' found
-- *** WARNING: You must have SDL_LoadObject() support for dynamic PulseAudio loading
-- Checking for module 'esound'
--   No package 'esound' found
-- Checking for modules 'bcm_host;brcmegl'
--   No package 'bcm_host' found
--   No package 'brcmegl' found
-- dynamic libX11 -> libX11.so.6
-- dynamic libXext -> libXext.so.6
-- dynamic libXcursor -> libXcursor.so.1
-- dynamic libXinerama -> libXinerama.so.1
-- dynamic libXi -> libXi.so.6
-- dynamic libXrandr -> libXrandr.so.2
-- dynamic libXrender -> libXrender.so.1
-- dynamic libXss -> libXss.so.1
-- dynamic libXxf86vm -> libXxf86vm.so.1
CMake Error at vendor/sdl2/cmake/macros.cmake:28 (message):
  *** ERROR: Missing Xext.h, maybe you need to install the libxext-dev
  package?
Call Stack (most recent call first):
  vendor/sdl2/cmake/sdlchecks.cmake:413 (message_error)
  vendor/sdl2/CMakeLists.txt:1127 (CheckX11)


-- Configuring incomplete, errors occurred!
See also "/home/rico/TIC-80_off_[cmake ..]/build/CMakeFiles/CMakeOutput.log".
See also "/home/rico/TIC-80_off_[cmake ..]/build/CMakeFiles/CMakeError.log".
rico@piOS-xfce:/home/rico/TIC-80_off_[cmake ..]/build $ 
`

I confess that I don't understand what I'm missing so that I don't make mistakes.
If it helps, I'm not under "raspbian classic" but under "raspbian lite XFCE".
Of course, I didn't try "Make -j4" 😉
