### ISSUE TITLE
malloc(): invalid next size (unsorted) when compiling on Raspberry Pi 4 - 4 Gb

### ISSUE THREAD

**Issue by jmcerrejon** [nesbox/TIC-80#1151]
I've tried to install on a clean Raspberry Pi OS 32 bits. App compilation it's OK but when I run for example /build/bin/toc80 I get this message:

malloc(): invalid next size (unsorted)
Aborted

I follow the instructions from [#1017](https://github.com/nesbox/TIC-80/issues/1017)

**UPDATE:** `sudo cp /opt/vc/lib/libbcm_host.so /usr/local/lib` did the trick

**Comment by jmcerrejon** [comment]
More info: [Here](https://github.com/jmcerrejon/PiKISS/blob/master/scripts/emus/tic-80.sh) the script I made. I tried a Raspberry Pi OS based distro called Twister OS and it has no problem there.

**Comment by farvardin** [comment]
Sorry for being picky about vocabulary, but your problem is not during compilation, as your title could suggest, but during run time.

I've tested with a recent version of raspbian 10 (kernel 4.19.97), the compilation went fine, but I got this malloc error too during run time. 

On another older version of raspbian 10 (kernel 4.19.57) which I have on another SD card, on the the same Rpi4 device, the binary I've just compiled on kernel 4.19.97 could be run without problem.

I suppose (but I'm not sure), it could be related with some settings in the config.txt in the /boot folder. There you can pass some arguments which could affect the GPU. Maybe you could try to change some of them. What is the kernel version of Twister OS?

Now if I remember well, on Linux Intel x86, I got a similar problem: the binary was running fine on most of my computers, but on one of them, I could crash during startup. Then if I freed some memory (by closing the browser for example), I could launch TIC-80 again.

**Comment by farvardin** [comment]
now I've tested the most recent system with kernel 4.19.97 on a Rpi 3 device, and it ran fine.

I've edited config.txt and commented the dtoverlay=vc4-fkms-v3d and max_framebuffers references:

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
**#**dtoverlay=vc4-fkms-v3d
**#**max_framebuffers=2

On my rpi4 it works too. Probably the rendering of video might be affected this way... but TIC-80 should work now.

Maybe this bug could be corrected in the code of TIC-80, probably some sort of optimisation to do. I'll search next week if it was really the same error on the x86_64 computer as well...

**Comment by jmcerrejon** [comment]
Yes, the app runs fine with those lines commented. At least you found the issue. Let it open for devs If they want/can to fix it. Thank you so much!
