### ISSUE TITLE
[FR] Use LuaJIT instead of regular LUA?

### ISSUE THREAD

**Issue by vanfanel** [nesbox/TIC-80#1215]
Hi there!

I have been trying TIC-80 on the Raspberry Pi 4 this morning, and I noticed some games are eating a LOT of CPU, enough to bring a double-buffered RA to it's knees (triple buffer works fine with high CPU usage, but adds input lag).

So, is there a reason why you don't use LUA-JIT instead of regular LUA? LUA-JIT is a lot faster! Could be an optional configure/build option, too.

It may help with https://github.com/nesbox/TIC-80/issues/1205

**Comment by nesbox** [comment]
Hi, 
TIC based on Lua 5.3 and as I know LuaJIT stuck on Lua 5.1 and isn't going to upgrade.
BTW, Did you build TIC yourself for RPi4 or use a prebuild version?
Thanks.

**Comment by vanfanel** [comment]
@nesbox I have bulit my own libretro version.

**Comment by vanfanel** [comment]
@nesbox I would also like to ask you: Do you know why some games bring  the Raspberry Pi 4 to it's knees? CPU usage in some games ("FPS-80" is the most notorious case) is 100%, while in others (like the awesome "Witch'em" it's pretty low.
Now, I could think it's because of some math functions (trigonometric probably) being used in "FPS-80", but other 3D games like "Gotta Go Fast" don't use up all CPU, keeping in a sane 22% all the time.
So, what is going on with those CPU-abusing games? Any idea?

CPU overuse in the libretro core means audio goes to hell :-1:

**Comment by RobLoach** [comment]
The libretro core uses libretro's audio/video callback to set the frame speed:
https://github.com/nesbox/TIC-80/blob/master/src/system/libretro/tic80_libretro.c#L263-L277

If the computation on a frame takes longer than what the FPS is expected, it results in the sound getting messed up. I was experimenting with using the [frame time callback](https://github.com/libretro/libretro-common/blob/master/include/libretro.h#L674-L682) instead, but it made the implementation more complex. The other thing that would be interesting to check out is allowing games to use 30 FPS instead of 60.

If you're interested in testing more, I did put together some bunny-benchmark utilities. Here's [Bunnymark in Moonscript/Lua](https://tic80.com/play?cart=989).

**Comment by nesbox** [comment]
Also, LuaJIT doesn't work in the browser :(
It seems it's not our client at all.

**Comment by fry-guy** [comment]
Hello. Has there been any development here? I've also noticed the slowdown issues with Shadow Over the Twelve Lands. Strangely, the issue doesn't exist with the 0.90.1477-dev version of this core, but the game crashes if you try to load it after saving a game. The save games work with 0.90.1579-dev, but the slowdown is bad.
