### ISSUE TITLE
feature: forcing crt effect in all version (including web) using metadata

### ISSUE THREAD

**Issue by superogue** [nesbox/TIC-80#1294]
Hi,

Maybe it would be a nice idea / easy to implement to enforce CRT effect by adding something like -- option crt in the metadata. This can be extended for other options in the future

**Comment by RobLoach** [comment]
Enforcing options on the user is a bad design choice. I'd rather the client be responsible for toggling the CRT filter rather than the game. In addition, SDL, Sokol, and libretro, are clients that don't implement the filter, so the game asking to enable the CRT filter wouldn't do anything.

Having the game tell the client how the client should behave seems backwards.

**Comment by nesbox** [comment]
Totally agreed with @RobLoach, you can't toggle CRT from the game, sorry.
Thanks.
