### ISSUE TITLE
Request: Add support for numpad inputs in key function

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1452]
Currently the numpad can't be accessed using `key()`. I imagine adding support would only be a matter of updateing `keycodes.inl` with some new codes and updating the docs. This would make playing with more users more easily possible etc

**Comment by nesbox** [comment]
Also, add the numpad arrow keys support

**Comment by cdwfs** [comment]
+1 to this request; I have a 4-player arcade panel which (confusingly) sends the numpad variants of PageUp (Numpad9) and Insert (Numpad) for player 3's "up" and "down" buttons. Due to this issue, this manifests as the vertical axis of P3's joystick not being recognized by TIC-80 as keyboard input.

I'll see if I can figure out enough to put together a pull request.
