### ISSUE TITLE
Raspberry Pi 4 model B: baremetal version didn't work (no signal on HDMI cable)

### ISSUE THREAD

**Issue by PetruCHIOrus** [nesbox/TIC-80#1534]
## I tried running the baremetal version of tic-80 on my raspberry pi 4 model b.
The following steps were taken:

-  Micro SD is formatted in fat32
- The files are copied to the root of the memory card
- The memory card is installed in a single-board computer
- The HDMI cable and power are connected

No image appeared on the TV screen. The bootloader of the computer did not appear, there were no errors, which means that the computer started successfully, right?

Is this version currently compatible with the raspberry pi 4 model b? Is it possible to change the settings file in the root of the sd card and solve the problem with the missing image?

**Comment by PetruCHIOrus** [comment]
![photo_2021-08-02_14-02-42](https://user-images.githubusercontent.com/39710644/127870415-38461908-5629-4949-b4ef-f6c59352360d.jpg)

video/audio working now

**Comment by PetruCHIOrus** [comment]
> 
> 
> 
> video/audio working now
keyboard will check later, I don't have gamepad for check how he work

**Comment by nesbox** [comment]
Added `tic80-rpi4-baremetal` build here 1afcf31

**Comment by Kyuchumimo** [comment]
![IMG_20210815_225348](https://user-images.githubusercontent.com/74131798/129513198-12a787de-0930-410c-ac38-6953a522b099.jpg)
It works well. It also works on Composite Video, but slower, perhaps because when activating the composite video output, the CPU clock frequency is decreased by the use of enable_tvout=1 on config.txt
