### ISSUE TITLE
Copy & paste a sprite doesn't copy flags

### ISSUE THREAD

**Issue by paul59** [nesbox/TIC-80#1535]
State of flags isn't copied when copying a sprite to another position on the sprite sheet. Applies whether in advanced or standard view.

Version: 0.90.1723 Pro (9c38a80)
(on Linux)

**Comment by joshgoebel** [comment]
@paul59 Has this ever worked or this is a feature request?

**Comment by paul59** [comment]
> @paul59 Has this ever worked or this is a feature request?
> 
> It's also not immediately clear to me that this is desirable behavior or what everyone would expect to happen by default... gets to the question of "what is a sprite"... off the top of my head I feel like I'd only expect the image data to be copied (esp if the sprite I was copying to already had flags set).

I don't know if it was the case in earlier versions I'm afraid so I suppose it could be a feature request!

I encountered it in making a game for Low Rez jam (https://mr-happy.itch.io/crowd-sauce): I'd made around 30 sprites for the characters and used the flags to indicate certain features, for example red hair or gold buttons. I decided to add another lot of items but my sprites weren't in a sensible position in the sprite sheet so I decided to copy and paste them. When things didn't work as expected I went straight to the flags and found they weren't properly set.

I imagine most people will use flags to indicate special tiles/sprites or differentiate between sprites that look the same but have slightly different properties. Either way they are an integral part of the sprite's data since they can be set in the editor just like pixels so should probably conform to copy/paste. I can imagine a scenario with many detailed tiles for a map where some new tile has to be added to the spritesheet - it would be painful to have to manually reset all the flags. I'm making the assumption here that users design chunks of artwork in the sprite editor with related pieces next to each other ie in a 16x24 sprite for a door the sprites would be drawn in the spritesheet as they appear in the game, rather than in sprite ID 1 to 6.

Just my opinion :D

**Comment by joshgoebel** [comment]
Would flags be copied even if they weren't visible (were toggled as hidden)?  I worry about what does a user think they are copying when they hit `Cmd-C`... for me I've never once thought it included the flag data... probably because I'm usually looking at the *right hand side* of the view... finding one sprite, finding the target location, pasting it there... so I'm thinking *purely in terms of graphical data*... not any other data that might be attached to the sprite.

I can certainly see the usefulness of this in some situations though... this is a hard one. :)

I think if we do this someone is going to post an issue saying all their flags were destroyed when they were copying sprites from one place on the sprite sheet to another... honestly it feels like something a toggle is needed for but I hate to add more UI for this.

**Comment by paul59** [comment]
> I think if we do this someone is going to post an issue saying all their flags were destroyed when they were copying sprites from one place on the sprite sheet to another... honestly it feels like something a toggle is needed for but I hate to add more UI for this.

But that's exactly why I think the flags _should_ be copied - I copied a number of sprites from one place to another and all the flag data was lost (or at least left behind and therefore applied incorrectly to a different sprite that occupied that ID). I think the question is: do the flags 'belong' to the sprite ID or the sprite image. Currently they're attached to the ID, so if you set flags and move the sprite elsewhere the flags remain set on the original ID. That's also the case if you cut rather than copy. I think that's more likely to create confusion/errors than moving them with the image.

Yes, I think the flags should be copied even if 'hidden'; the user must have set them and want them to apply to that particular sprite after all.

I suppose alternative key combinations could be implemented to provide the option of copying the flags or not eg ctrl+c and ctrl+shift+c but then what should ctrl+x do? 

I can see that in designing tiles for a map it might be useful to leave the flags in situ but to my mind having the flags and the sprite pixels linked together seems the better option.

**Comment by joshgoebel** [comment]
I leave this up to the wisdom of nesbox.  It's hard for me to imagine what (if anything) is truly "correct" here as it seems some users will get bitten either way.  I count myself in that group because I would not expect it to work this way by default.  I suppose users will learn to cope whichever way we go.

**Comment by nesbox** [comment]
I'm for toggle button to control the copying behavior, the only question
Is copying of flags should be enabled by default?

**Comment by paul59** [comment]
> I'm for toggle button to control the copying behavior, the only question Is copying of flags should be enabled by default?

If you implement a toggle I'd say no - it makes more sense if you have a button or checkbox that effectively says 'Copy Flags?' for it to be off (no copy) by default. If there's no toggle in the UI  I'd say copying should be enabled by default.

**Comment by nesbox** [comment]
Added sprite flags copy/paste ea464f5c097677fa4ca1021c4dde964554bbdc05
