### ISSUE TITLE
[0.90] Cannot activate CRT effect

### ISSUE THREAD

**Issue by scambier** [nesbox/TIC-80#1566]
Platform: Windows 10

Pressing F6 does not activate the CRT effect, and setting it to `true` from the config cart doesn't work either.

**Comment by symbolisch1234** [comment]
I am on Ubuntu, and for me it works in the web player on https://tic80.com/play, but not locally. Both are 0.90.1723

(I am wondering if this is a pro-version feature? I only have basic Tic80.)

**Comment by ChildishGiant** [comment]
When running on the website it uses WASM which is a different architecture than the version you download.

**Comment by nesbox** [comment]
The 0.90 version was released without CRT filter support because we got a lot of complaints from people. The reason is that the `SDLGPU` library which we use to show the CRT effect is very unstable on various platforms. I hope we will add the ability in `v1.0` to switch `SDL2 <-> SDLGPU` rendering on the fly in next version, this should fix the problem.

**Comment by nesbox** [comment]
d07ad7fd775ceb001c86ffe8f41cc19f3221329f
fixed `CRT_MONITOR` option
added `--soft` command-line parameter to enable software rendering using SDL2 only, instead SDLGPU
