### ISSUE TITLE
The TIC-80 gfx API from a retro Fantasy CPU perspective

### ISSUE THREAD

**Issue by joshgoebel** [nesbox/TIC-80#1678]
Related: #1007 #1661

Opening this thread because #1661 was really veering off in an entirely different direction than I hoped.  My original issue was entirely within the context of TIC-80 as a high-level abstraction that runs high-level code and whether the API should pretend/desire to be more like "magic hardware opcodes" or "assembly language routines"... the latter proving hard to duplicate in software, while the former (by requirement) would be easy.

In this topic we can focus on the API (and how to represent it in hardware/software) from a low-level fantasy CPU perspective... if the VM was not Lua, but rather something like a DCPU-16 or ATMega core... how would one access an API like `line` or `spr`?  I see two major possibilities.

FYI: I'm going to specifically avoid talking about audio here as I think that's a subject on it's own...

---

### Very simple hardware

We have a CPU. There is no GPU.  The video RAM is somehow directly mapped to the simple video hardware directly (like on early PCs)... where just writing into the video RAM immediately updates the screen output (on the next vsync)...  ALL of the graphic API calls would need to be provided via ROM API like [DOS Interrupt 21](http://spike.scu.edu.au/~barry/interrupts.html)... which means `line` would not call out "magic C code" - it would use not `tic_api_line` (like all other languages) - rather it would rather be implemented as a graphics ROM in the native instruction set of our CPU.  

This consideration alone might mean our addressable "ROM"/program space is more than 65kb... perhaps 65kb of cartridge ROM for user programs plus an additional ROM to hold all the graphics co-routines.  At boot time the graphics ROM would always be in place and the user ROM would slot into it's own memory address on the ROM side (assuming Harvard).

This would be frustrating to maintain long-term as every time we fixed a bug in the C graphics API the bug fix would have to also be duplicated in the graphics ROM assembly routines. This problem would get worse if we have more than one virtual CPU implementation. (example: [current bug](https://github.com/nesbox/TIC-80/issues/1532) with eclipse drawing, etc)

### More complex hardware

We have a CPU.  We have a GPU.  Note: This potentially would change the memory layout.  Things like VRAM, SPRITES, MAP, TILES are likely now in the GPU memory address space rather than the CPU.  Though perhaps we could say that our architecture seamlessly allows mapping this stuff back into CPU RAM address space.  Yet one could also imagine a world where software does NOT *directly* have access to this but would need to instead query the GPU.

IE `pix` could not be implemented as simply reading into RAM, but would have to request data from the GPU over a data bus of some kind, etc...  I think that's a bit less fun though and slightly against the TIC-80 "spirit"... it seems (for parity with existing languages) that the user should have the choice of using the existing API functions or  writing their own from scratch, with easy access to video RAM in the normal CPU address space.

I think this approach, meaning a discrete GPU but with it's memory mapped back into CPU address space, is much more compatible with TIC-80 as it stands now.  It would continue to leverage most of the existing C API code... ie, whatever GPU commands someone queues up to send to the GPU for a`drawPixel 0 0 color: 5` operation once they were sent over the fantasy data bus it would essentially just turn into a `tic_api_pix` call... 

---

Note, in no case do I think `line` (or other complex API graphics calls) should be CPU opcodes.  IE, we would not go the Chip-8 route of making `sprite` a feature of the CPU itself. `line` would either be just a subroutine somewhere in ROM:

```
load R0, 0 // x 
load R1, 0 // y
load R2, 3 // color
call gfx_line
```

...or a command issued over a data bus to a waiting GPU. IE: (assume out port determines with data port we're writing to)

```
load OUT_PORT, GPU_PORT
write OUT, PIX_DRAW_OPCODE
write OUT, R0 // x
write OUT, R1 // y
write OUT, R2 // color
```

**Comment by Anrock** [comment]
> Very simple hardware

> rather it would rather be implemented as a graphics ROM in the native instruction set of our CPU.

> This consideration alone might mean our addressable "ROM"/program space is more than 65kb

> This would be frustrating to maintain long-term as every time we fixed a bug in the C graphics API the bug fix would have to also be duplicated in the graphics ROM assembly routines.

Why write graphical primitives in assembly if from user perpective they're opaque? Just handle int21 in C code and call existing TIC functions and all those problems are gone.
```c
static void asm_api_interrupt(...) {
  switch (...)
    case INTERRUPT_LINE:
        tic_api_line(...)
  ...
}
```

> More complex hardware

> I think this approach, meaning a discrete GPU but with it's memory mapped back into CPU address space, is much more compatible with TIC-80 as it stands now.

I don't quite get what the difference. The only change is addition of some data bus / queue / whatever to issue commands via memory access and everything else is the same?

> IE pix could not be implemented as simply reading into RAM, but would have to request data from the GPU over a data bus of some kind, etc... I think that's a bit less fun though and slightly against the TIC-80 "spirit"

Can you elaborate a bit more about "less fun" and "spirit"? The only downside I see is backward incompatibility for old cartridges that write directly to VRAM. 

Backwards incompatibility can be alleviated with
a) Cart mapper option, i.e. something like `// mapper: default` which will map RAM/VRAM just as it is and `// mapper: new` which will expose registers into address space instead of full blown VRAM and generally alter memory layout any way we see fit in backwards compatible manner.
b) Basically same but with memory banking. Since we already have memory banking, we introduce ability to switch out VRAM space with usual RAM. Similar to mapper we can both have the cake and eat it too. But I dislike this option since it makes layout fragmented leading to lots of hassle of splitting code to "always present" and "transient". Not the kind of difficulties I want to have in fantasy console.

**Comment by joshgoebel** [comment]
> Just handle int21 in C code and call existing TIC functions and all those problems are gone.

I think you're assuming software interrupts in the CPU, which isn't a given since we don't know the CPU yet.  You still need a way to pass the data (registers, bus, etc) even if it was interrupt driven so I think my second "data bus" example would look a lot like a software interrupt example would. If it's all memory mapped RAM then you'd just be writing to RAM instead of registers, but otherwise, same idea.

> I don't quite get what the difference.

If there is no fantasy "discrete GPU" then there is no "just let the GPU do it"... so  `line` must be written in machine code that runs on the fantasy processor, and draws lines by writing to VRAM - not the  super fast C we have now.   So you'd have to have a compiled gfx ROM before you could even boot up a cartridge, etc...

And if you only meant what is the difference between mapping the GPU VRAM into address space and making it "inaccessible" then all the cool "poke to VRAM" tricks go out the window fi the VRAM is "hidden" behind the GPU... so one way or the other I think we'd want it accessible.

> Can you elaborate a bit more about "less fun" and "spirit"? 

I think a lot of the PICO-8/TIC-80 fun comes from writing optimize peek/poke "magic" routines... seeing how fast you can get them... just replacing everything with calls to a discrete GPU takes away that fun IMHO.

> The only downside I see is backward incompatibility for old cartridges that write directly to VRAM.

_Again, not relevant as there are no existing fantasy CPU cartridges._   I maintain that implementing fantasy CPU does not **require** greatly (or even even slightly) changing the representation of the system that's seen from the other runtimes. So I'm ignoring the comments about preserving backwards compatibility since I'm not sure I completely follow them anyways.

> I also dislike introduction of new data bus entity.

I think this decision partly depends on which CPU is selected.  I've been looking at the Z80 for example and it already has built in concepts and functions for talking to peripherals via I/O ports, etc... so if that was chose then I'd probably look at mapping the GPU access into the methodology of the Z80 - access via I/O mappings.  It can't **purely** be memory because you still need a way to dispatch/queue commands.  So I think this decision of "how to talk to the GPU" doesn't make sense until we first know what CPU we're going with.

It's also not either or.  You could dispatch commands via CPU I/O pipelines but also have VRAM mapping into CPU addressable address space.

---

I think you imagine there is some benefit to ALL the APIs going thru a "memory mapped" type of API and I believe this is 100% mistaken.  You've spoken as if all runtimes would adopt this underneath and this is just an unneeded layer of abstraction for ALL scripting VM runtimes.  Currently we have a tiny wrapper:

- `line` called in Lua
- `tic_api_line` called in C

You're suggesting:

- `line` called Lua
- some magic memory map ram and register modified to queue up the `line` command
- some other call/something to "dispatch" the command
- reading all those registers back out of memory, etc...
- finally `tic_api_line` called in C

_This does nothing but slow Lua down._  There is no benefit *UNLESS* Lua users wanted to sometimes use this memory mapped RAM directly themselves to avoid the API calls... and if it was just a dumb wrapper I can see no reason anyone would want to do that.

So this type of indirection ONLY makes sense when we're dealing with a "fantasy CPU"... and since there would be REAL speed and RAM limits on this fantasy CPU then the extra cost of the indirection there is already paid for... plus [some type of] "get the commands to the GPU" abstraction is truly here where-as it's not at all necessary in the higher level scripting languages.

**Comment by joshgoebel** [comment]
Even the fact that say we might have a 16-bit address space (Harvard or Von-Neumann) in our fantasy CPU (with the ability to page real RAM into certain segments) would have nothing at all to do with how any of the other runtimes see anything - they would continue to see the same happy 96kb 32-bit addressed(?) RAM they've always used - and will continue to use with no backwards compatibility issues at all.

That history layout MIGHT educate how the "REAL" RAM in the fantasy CPU is addressed though... ie if we ask the MMU to map 16kb of VRAM to address 0x2000... we'd tell it to find that VRAM at address 0 in our "RAM chips" (corresponding to the original TIC-80 ram layout).  To make addressing more than 64kb possible (for mapping REAL RAM to our limited 16-bit address speac) we can probably just map by 2 or 4 byte chunks of actual RAM... giving us total max (theoretical) RAM of 256kb.

**Comment by joshgoebel** [comment]
I also don't think it's clear how much real RAM TIC-80 has from a fantasy hardware perspective once we start talking a more real CPU, MMU, and mapped "real" RAM vs addressable space, etc.  Obviously we have large segments of RAM we *could* use if they aren't fulfilling their otherwise intended purposes (as the scriptable environments make it seem like the whole 96kb is fully writable).

But if you "unmapped" all the pseudo-device RAM (VRAM, Audio RAM, etc) out of the address space... I'm not sure you're left with much at all other than the 12,796 bytes at the end of RAM.  Is that all the actual RAM we can address without stealing from devices?  If someone wanted to write a BIG game using tons of sprites, tiles, map, etc... and tons of audio/music...

Is 12kb all that's left for data storage?  I mean that's not nothing... but... I wonder. :)

**Comment by joshgoebel** [comment]
> If you'd like I can prepare a table / specification for memory mapped GPU registers.

I'm curious to know what you actually mean by this.  Are you imagining that the graphics hardware has a dedicated `x`, `y`, `color` registers or some such vs just unnamed arguments that are passed to different commands?

**Comment by Anrock** [comment]
> I think a lot of the PICO-8/TIC-80 fun comes from writing optimize peek/poke "magic" routines... seeing how fast you can get them... just replacing everything with calls to a discrete GPU takes away that fun IMHO.

Hm, I thought calling ready-made API functions was always faster than making the same thing with peek/pokes since it's 1 vs. N calls. But okay, thanks for explanation.

> Again, not relevant as there are no existing fantasy CPU cartridges

Oh, I didn't thought about having memory layout depend on a cart language! That's even better, like a mapper but completely implicit! Indeed, my further comments about backwards compatibility are irrelevant with that.

However from that point we will have maintain (at least) two different layouts. Not sure how much of a maintaining burden it will be, but certainly a downside. And removing current layout goes against "fun" as you called it.

> I think this decision partly depends on which CPU is selected.

Important point here. Are we selecting **one and only CPU** that's deeply baked into TIC or we're trying to alter TIC in such a way that any CPU can be added, just like new languages? 

I'm judging (and was judging) from latter point of view. Which implies whatever we come up with should work with any CPU instead of being tailored to some single one.

> It can't purely be memory because you still need a way to dispatch/queue commands.

I don't see why you need special dispatch/queue commands. The way I see it

a) GPU executes any gfx operation in one CPU cycle. Therefore there are no queues and no need in dispatch/queue commands. This also aligned with how current languages work - when next line after `circle` executed - circle is already on the screen.

(We can say that GPU works way faster than CPU. For whatever reason, be it GPU having way higher frequency than CPU or GPU ISA is orders of magnitude more effective for graphics stuff. It doesn't matter from programmer POV)

b) In case we make GPU take some time to execute command then control register of GPU should be R/W and GPU will reset it to some "idle" (alternatively there can be a signal busy/idle bit) value after previous command is executed. So programmer will have to first read that control register and write new command only if value was "idle". In case GPU is idle programmer can either write a busy-wait cycle or maintain command queue right in RAM. So still there is no absolute need in dedicated dispatch/queue commands.

Personally I would prefer option a) for simplicity sake. But option b) is fine too if we want extra dials and knobs for fun.

> It's also not either or. You could dispatch commands via CPU I/O pipelines but also have VRAM mapping into CPU addressable address space.

True. But I don't see a point of having both (for fantasy CPUs) since I/O was not only about controlling GPU via mem access but also about freeing up address space.

> I think you imagine there is some benefit to ALL the APIs going thru a "memory mapped" type of API

Not really. As I've written multiple times they could, they could not. It's possibility, not requirement. Only ones that will have to are low level ones. High level ones can be left as is.

> You're suggesting:

It was more like this in case you didn't want to use wrappers:
* `line` called Lua
* `tic_api_poke` called multiple times to modify some magic memory map ram and registers
* one last `tic_api_poke` sees that command register was written to and calls `tic_api_line`
* `tic_api_line` calls `tic_api_poke` to reset command register when it's done.

Or, absolutely the same if you use wrappers:
* `line` called in Lua
* `tic_api_line` called in C

It's just a couple more of C calls, not more of LUA<->C calls and those C calls internal to `tic_api_*` so they could probably be replaced with direct array writes.

So I don't see how it can introduce noticeable slowdowns *even* if we go this way.

> And again, none of this remapping functionality is necessary for the scripting runtimes. You could expose it, of course

I would prefer to leave out memory remapping shenanigans unexposed even for CPUs for simplicity sake. "Here's layout for scripting languages (unchanged), here's different layout for CPUs" and that's it, no MMU control, no memory mapping configs. Everything's static and fixed.



> But if you "unmapped" all the pseudo-device RAM (VRAM, Audio RAM, etc) out of the address space... I'm not sure you're left with much at all other than the 12,796 bytes at the end of RAM.

If you unmap everything than you have 64kb of addressable space (assuming we make 16bit address bus for simplicity).
Suppose we made all the devices memory mapped with only a couple of registers per device to interact with. I'm totally making up this number but overall I/O space would be probably less than or around 128 bytes. 
Add interrupt vector of generous 256 bytes (I'd say maximum we will need is 16 or 32).
The rest 65535 - 128 - 256 = 65151 bytes are free to be mapped to RAM chips for code and data. 
Sega MD had 64kb, so I'd say we're good. And that's even without memory banking.

Also, while we're talking about memory layout it would be nice to have as contigious as possible. Hypothetically
```
0x0000 RAM
0xDE7F Banked space
0xFE7F I/O space
0xFEFF Interrupt vector
```

> Is that all the actual RAM we can
"safely" address without stealing from devices? If someone wanted to write a BIG game using tons of sprites, tiles, map, etc... and tons of audio/music...

I'd say leave sprites, map and tiles memory alone as is. It's implicitly connected right into GPU, so it's not taking up any address space and accesible only via GPU registers.

> I'm curious to know what you actually mean by this. Are you imagining that the graphics hardware has a dedicated x, y, color registers or some such vs just unnamed arguments that are passed to different commands?

Yes, something like this. 1-byte command register and then N registers for arguments which values are interpreted differently depending on a command. Then maybe some other registers like clip one. Am I wrong?

**Comment by joshgoebel** [comment]
> Hm, I thought calling ready-made API functions was always faster than making the same thing with peek/pokes since it's 1 vs. N calls. But okay, thanks for explanation.

Yeah, but it's not the usually "same thing" people are building.  Often you're building fast BIT-BLT routines that are applying shading effects or some such - there are no built in equivalent API commands and peek/poke in a tight loop is WAY faster than pix because it doesn't have to calculate the coordinates in RAM over and over... you can just `+1` the memory address.

Not being able to apply these effects directly against VRAM would be a huge loss.  So any virtual CPU needs to have the ability to page VRAM into addressable space - not just access it via a command driven "GPU".

> However from that point we will have maintain (at least) two different layouts. Not sure how much of a maintaining burden it will be, but certainly a downside. 

I also don't know how true this is... The current layout could remain "canonical" and used as the "absolute" addresses of the RAM chips... any CPU with only 64k of addressable RAM will need to support paging - so the CPU would just be paging segments of RAM into it's address space as necessary... this does not require a "new layout"...

Now it may be that once we have a real fantasy CPU that it causes us to go back and rethink the RAM/addressing in general - what our RAM *really* looks like - once a fantasy CPU forces us to think about it a bit harder in terms of RAM, devices, etc... but I don't see that as being a requirement.

>  Are we selecting one and only CPU ... or ... any CPU can be added, just like new languages?

I don't believe in over abstraction.  It's easy to lose our way (and build a lot of junk we don't need) if we're being a "super generic CPU interface" when all we need is an interface for the Z80, say... so I'm open to keeping some of the larger concerns in mind but I think the first CPU interface built should be tightly integrated.

Making it generic should happen when it comes time to add a second CPU.

> I don't see why you need special dispatch/queue commands. 

You do because otherwise there is no way to know when you're doing writing to RAM and actually want the commands you wrote to be executed.  You need a dispatch ("go now") even if the queue size if 1.

Regarding how the GPU "appears" to work I'd say "infinitely fast" is fine enough for our uses... I don't see any value in forcing fantasy CPU users to add polling/idle loops waiting for the GPU to "finish" it's work... 

>  But I don't see a point of having both (for fantasy CPUs) since I/O was not only about controlling GPU via mem access but also about freeing up address space.

See my very beginning note about people doing shading effects and needing access to the raw VRAM for tight read/write loops.  Very common for advanced graphics on PICO-8 and you'd need it for the same reasons here... we don't need to "free up address space"... it should rather be pageable via a simple interface. Software that doesn't need the VRAM doesn't need to page it in.

> It's just a couple more of C calls,

_Which means it's slower_, which is what I was saying.  More calls = more slow.  Doing quite a bit of memory/mapping work in-between `line` and `tic_api_line` is going to be measurably slower.  How much slower exactly, I dunno... but seeing as there is little to no benefit to be gained then even 1us slower is too slow IMHO.

> I would prefer to leave out memory remapping shenanigans 

I don't think "shenanigans" is a fair word. :-)

> 65151 bytes are free to be mapped to RAM chips for code and data.

And we have 96kb of RAM that needs to be accessible.  So being unable to "map at will" means the fantasy CPU is inferior to the scripting environment in its ability to access memory.  People can and do write custom sprites/map renderers (I have for one)... so that alone requires access to SCREEN + TILES + SPRITES + MAP... 64kb... and now there is no addressable space for audio, keyboard/controller IO, etc...

I see any type of fixed layout a no-go unless we have 18-bit address bus and the entire RAM is accessible just as it is for scripting environs.

> nice to have as contigious as possible. Hypothetically...

I don't feel like this is worth discussing until we're much closer to something real.  I agree the design of RAM is a bit "scattered" now but that doesn't necessarily mean we just "invent something entirely new" for a fantasy CPU. :-)

_Particularly when we don't even have a CPU in mind yet!_  If we build something custom that has > 16-bit addressing then this isn't even a problem at all... perhaps not all possible CPUs should even be considered for support...

> It's implicitly connected right into GPU, so it's not taking up any address space

As I pointed out this doesn't work as it breaks a lot of the ability to write custom graphics routines...

> 1-byte command register and then N registers for arguments which values are interpreted differently depending on a command. 

I don't think that requires mapping out.  I think you just described it. :-)  Simply: You have a command register, argument registers. and then all the existing hardware VRAM registers: border, shift, clip, etc...

**Comment by Anrock** [comment]
> Not being able to apply these effects directly against VRAM would be a huge loss. So any virtual CPU needs to have the ability to page VRAM into addressable space - not just access it via a command driven "GPU".

Ok, agreed. But I hope you're not talking about MMUs, memory map configs and adress translations here. IMHO it should be done with bank switching - it's more simple, more retro-true and we can even make it CPU-agnotic by having memory mapped single byte "memory bank register" in which you write a bank index and it's mapped into address space. We'll just reserve banks 0 to N for VRAM.

Overall I'm strongly leaning to "move as much as possible out of CPU ISA into dedicated memory mapped registers". Advantages are that memory layout is the same for various CPUs, CPU implementers have to implement less things and CPU instruction sets are smaller and simpler for programmers. And that's why I'm sorta against a notion of data bus - not all CPUs have I/O ports in their instruction sets. Memory mapping is more universal.

> You do because otherwise there is no way to know when you're doing writing to RAM and actually want the commands you wrote to be executed. You need a dispatch ("go now") even if the queue size if 1.

Still not clear to me. If you execute `store GPU_REG_CMD GPU_CMD_LINE` it's already means "go now". Why have separate instruction for that? Or what do you mean exactly by queue/dispatch commands?

> Regarding how the GPU "appears" to work I'd say "infinitely fast" is fine enough for our uses... I don't see any value in forcing fantasy CPU users to add polling/idle loops waiting for the GPU to "finish" it's work...

Good. Infinite-fast GPU it is then.

> Which means it's slower, which is what I was saying. More calls = more slow. Doing quite a bit of memory/mapping work in-between line and tic_api_line is going to be measurably slower. How much slower exactly, I dunno... but seeing as there is little to no benefit to be gained then even 1us slower is too slow IMHO.

I still don't believe couple of indexed array writes in some of functions would be even measureably slower, but ok. It wasn't mandatory anyway and having it for CPUs only is fine by me.

> And we have 96kb of RAM that needs to be accessible [...]

I see. 

Welp, if everything is mapped or available via memory banking would it be considered okay then? See my first answer in this comment. Reserve more banks for I/O and resources. Single "memory bank register" can hold as much as 256 different values so we have a lot of space to bank, just have to think a little how to bank them conveniently for programmer. Something like Commander X16:

![out](https://user-images.githubusercontent.com/1689392/141012272-5dad82fd-00bf-4d54-a4ca-b32353f71743.png)

Hardware registers in I/O space, VRAM, resources and other "bulky" things in first N banks. Rest is RAM.

Why I'm so pro-banking: I'm sorta against more than 16-bit address bus since it adds various address modes and personally I find them ugly. Having everything addressable in direct mode is great.

> I don't feel like this is worth discussing until we're much closer to something real. 

Discussing on high-level worth it, I think. We don't want to add a third revised layout after it goes in the wild, don't we?

> I agree the design of RAM is a bit "scattered" now but that doesn't necessarily mean we just "invent something entirely new" for a fantasy CPU. :-)

We're going for different layout specific for CPUs, as I understand, so why not make it "entirely new" and as good as possible?

> I don't think that requires mapping out. I think you just described it. :-) Simply: You have a command register, argument registers. and then all the existing hardware VRAM registers: border, shift, clip, etc...

Good! We'll get into details later then.

**Comment by tehologist** [comment]
I do not agree with memory mapping all the devices, the memory is already mapped. The limited set of functionality supplied with current functions is not that different from the rom mapped routines in the C64 which had hardware sprites and audio. The CP/M systems based on z80 also used routines in rom (BIOS) for IO, this kept the calls to writing text and drive access portable between systems. What would end up happening is people would copy/paste the same routines for calls to mimic the current api and just waste valuable memory doing so. I am currently working on a small cpu for my own use, as I am trying to get Tic-80 working on a pico system handheld which has very little ram. I have made a lot of progress and will share once I am complete, my goal is to get everything working in the existing 12K at the end.

**Comment by joshgoebel** [comment]
> I do not agree with memory mapping all the devices, the memory is already mapped.

This statement makes no sense to me.

> this kept the calls to writing text and drive access portable between systems

Obviously not a concern here.

>  What would end up happening is people would copy/paste the same routines for calls to mimic the current api and just waste valuable memory doing so.

I think there are very good reasons we'd likely ship both - a tiny ROM but ALSO the underlying hardware explanation for how it all works.  Take a DCPU-16 style example of rendering a colored pixel to the screen at 5,5.  We use pretty variables just because they are available on that architecture.

```js
set PUSH, 5 // x
set PUSH, 5 // y
set PUSH, 15 // color
jsr pix_write
```

This is a nice clean API where we push arguments (in order) onto the stack...  But the routine being called is still in RAM somewhere.  What does it do?  I argue it should talk to the hardware (as much as the given CPU architecture allows).  Most CPU architectures have opcodes to talk to hardware if it's not fully memory mapped.  So here is what I think `pix_write:` should be:

```js
pix_write:
  set PUSH, J
  set PUSH, I
   // write to the graphics command buffer in RAM
   set J, GFX_CMD_BUFFER
   // peel arguments off the stack
   set I, SP
   // skip over the two words we pushed into the stack
   add I, 1
   // this will also increase I a second time
   sti [J], GFX_DRAW_PIXEL_OPCODE
   // copy all 3 argument over to the command buffer, store and increment
   sti [J], [I]
   sti [J], [I]
   sti [J], [I]
   // send a hardware interrupt to the graphics card
   HWI GFX_CARD
   set I, POP
   set J, POP
```

The only facility DCPU-16 seems to have to talking to hardware is `HWI` to send a interrupt (with no data), so I presume that memory mapped RAM (of some type) is required, and I accounted for that with a `GFX_CMD_BUFFER` area of RAM.

Now having access to `pix_write`, why would someone want to talk to the GPU directly?  I dunno.  Having `pix`, why do people still want to write directly to VRAM.  One presumes that in some cases it's faster or allows you to more easily do something that simply isn't possible otherwise.  For example our GPU could easily have a "stream data" CMD that allows you to define a square of the display and then just fire 200 bytes straight into VRAM, letting the GPU worry about pixel coordinates, etc... this would be much faster/simpler than using `pix` or even accessing RAM and trying to calculate the proper memory offsets.

To me I think once you have a "real" CPU in the mix it makes sense to remove another layer of the "magic".  For what is the alternative?  Once someone jumps to `pix_write`? What will they find there in RAM?  Is that just a "magic" location with no code that TIC-80 then does "magic" ?  I think that would be unfortunate and that there is no need for the magic when it could just as easily be code.  Even if the answer is "our CPU and GPU are kind of one big thingy" then at that memory location you'd find graphics opcodes for the GPU... not just "nothing"...

I don't think that's best though (making every API call an opcode on the CPU)... I do think (for simplicity and completeness) it makes sense to make those "opcodes" available on the GPU itself... so in that case the question remains: How does the CPU talk to the GPU?  _Just saying "use the included ROM" doesn't answer that question._ It just pushes it upstream.  Someone should be able to look inside the ROM and see how it talks to the GPU...

Right now I think the "ROM" should be a simple wrapper layer between whatever argument passing paradigm we choose for the ROM API and the underlying graphics hardware, as shown in the example above.

**Comment by joshgoebel** [comment]
And of course someone could forgo all this and write directly to VRAM. I'd include a sample, but it'd be a bit more painful on the DCPU-16 where everything is word addressed, you'd have to read 4 pixels out (word, 2 bytes), mask your pixel, set it, then write it back... Actually DCPU-16 write/read directly from an address in a single opcode helps you some, but you'd still have to calculate which nibble you needed the mask for, shift your replacement nibble into place correctly. Not fun.

Our nibble by nibble graphics RAM layout certainly isn't much fun once you start thinking about it at a machine level.

**Comment by TheRektafire** [comment]
Personally I like the idea of having bankswitching and everything being memory mapped as well, though 256 pages of 64K is a bit much for a fantasy 8/16 bit console imo 😂 Though then again it means people can use pretty much however much ram they want to use so that's good I guess since it means you can make more complex games that take up more ram like games with procedural generation if you want. If the GPU is infinitely fast then it might be best to move the actual api code into the cpu too though if it stays outside on it's own then you could do some interesting things with it like instead of writing to vram pixel by pixel with the cpu you could just get the GPU to create lines or squares or triangles very fast and you could easily do a 3d wireframe/vector graphics type game. As for which cpu to use it would probably be best to use one with good documentation, a fairly simple instruction set so people who potentially want to go the asm route can learn it easily, and community support, the z80 or 6502 or motorola 68k could be good in that regard, the 68k also has the advantage of having a larger data bus than the 6502 or z80 so it could address more stuff without bankswitching fwiw so that's probably the one I would think about going with first personally and it seems like there's at least 1 other person who agrees with me since theres another issue where someone is suggesting adding 68000 support :p If you wanted to keep the bankswitching with the 68000 you could just make the memory loop every 64k so you have to switch to get a new 64k in to use and of course the hardware register required for switching the bank would be bank independent so you could always use it
