### ISSUE TITLE
`vbank(1)` breaks the studio after exiting the game

### ISSUE THREAD

**Issue by Weeppiko** [nesbox/TIC-80#1717]
After exiting a game using `vbank(1)` the studio becomes completely unusable and the `bank1` palette will also not work anymore if you try to play the game again, it just uses the same as `bank0`
![video5](https://user-images.githubusercontent.com/88540876/144693004-5e770986-806d-4193-9936-599df930aea7.gif)

**Comment by joshgoebel** [comment]
Is this perhaps because of how we handle vram and vbank as separate things - and if we're losing track of which is which.

Anyone who's worked with systems a long time knows that there are only two numbers: `1` and `many`...  I know we THINK there will only ever be 2 banks of VRAM... but I wonder if this wouldn't have been better to just have two actual banks of VRAM (in an array, etc)... and then a pointer to whichever is active... we'd still have to `memcpy` to TIC "RAM" during vbank so that our fast `mem*` calls work without a layer of abstraction, but I think a lot of other code paths would be simplified... right now we have annoying code like this inside hot paths (like per-pixel rendering):

```
static inline tic_vram* vbank0(tic_core* core)
{
    return core->state.vbank.id ? &core->state.vbank.mem : &core->memory.ram.vram;
}
```

A conditional shouldn't be needed at all if vbank0 and bank1 were just pointers to discrete areas of RAM - that do NOT swap.  IE you'd have:

- TIC VRAM (mapped memory)
- bank0
- bank1

From C you could access bank0 and bank1 as needed (read only), but all writes should be done to the  memory that's paged into TIC VRAM...  so `bank(1)` would be essentially:

```lua
-- if not already vbank 1
memcpy(VRAM, bank0)
memcpy(bank1, VRAM)
```

IE, switching saves our "current" VRAM to it's appropriate bank, then swaps in the new bank.  The cost of doing it this way is 16kb extra of memory.... which seems fine considering previously we had a HUGE array (of bytes!!!) just to store the bit mask of OVR - that we just got rid of.

Am I missing something about why this couldn't be simplified along these lines?

**Comment by joshgoebel** [comment]
N/m, the banks aren't read safe either because you can modify the mapped memory... so I think perhaps we need things like `vbank0()`... but we should CACHE that call as long as possible:

```c
tic_vram* vb0 = vbank0(core);
tic_vram* vb1 = vbank1(core);
```

IE, get these pointers once at the beginning of the loop rather than per-pixel.  Again it's not clear to me that the compiler could do this optimization for us since there are a lot of other function calls happening in-between...

**Comment by nesbox** [comment]
Fixed here cd90239
Thank you.

**Comment by nesbox** [comment]
> get these pointers once at the beginning of the loop rather than per-pixel

What if the user decides to change `vbank` during the scanline, it should be once at the beginning of the scanline, anyway, I removed these pointers switching here https://github.com/nesbox/TIC-80/commit/cd9023959117a55726bba2aeef3500dd1231ad45#diff-b12741dd50b1e0ba0c71a5d8d1661199e19c6b5abe8133846ae997d577b97f68R544-R550 and current vbank uses the first layer, the other uses the second layer.

**Comment by joshgoebel** [comment]
> What if the user decides to change vbank during the scanline

I never considered that but it wouldn't bother me if that was simply "disallowed" or "not supported".    But why would that matter at all if they were fixed?  If the layering was static then vbank1 would always draw "on top"... it wouldn't matter which was "active" or not... unless I'm missing something?

> and current vbank uses the first layer, the other uses the second layer.

Well, that's an entirely different way of thinking about it. :)
