### ISSUE TITLE
Shift+Enter to "play music from now" only works in tracker mode

### ISSUE THREAD

**Issue by blinry** [nesbox/TIC-80#1838]
[This line](https://github.com/nesbox/TIC-80/blob/612fc62178e747a7cb793af0bcf127871cd0f3ba/src/studio/editors/music.c#L1438) checks that the music editor is in tracker mode to make Shift+Enter "play the music from now". In the piano mode, it just plays the current frame.

This is not what I'd expect, since the "play from now" button works as expected. Is there a reasoning behind this differentiation, or can we remove it?

**Comment by nesbox** [comment]
The reason is that we don't have a selectable row in piano mode and we can't start playing from it :)

**Comment by john-m-dubs** [comment]
jumping on this issue since mine is tangentially related: it would be really nice to have a hotkey that plays the song from the current point (not just looping the same frame). right now (as far as i know) you can't hear how one frames leads into another without playing the entire song from the beginning. this makes it very hard to compose a song!

e.g., these are the current hotkeys and i'd like to add the one in bold:
spacebar: play song
enter: play from
shift+enter: play frame from current point
**shift + spacebar**: play song from current point (e.g. don't loop inside the frame, have one lead into another)

**Comment by nesbox** [comment]
Or we could add a button to the toolbar to enable/disable looping.

**Comment by Gate88** [comment]
> Or we could add a button to the toolbar to enable/disable looping.

yep that works too! anything that lets me play the song from the current point but not get stuck in the current frame would be a big help. (still the poster from above; was accidentally in my test account before).

**Comment by blinry** [comment]
> The reason is that we don't have a selectable row in piano mode and we can't start playing from it :)

Oh, I didn't realize that's how it would work in tracker mode!! :) In piano mode, could we change the button and the source code to start playing from the beginning of the current frame, but then keep playing after that? That's what I would've expected. :)

**Comment by nesbox** [comment]
So, we're adding a `loop on/off` button and removing `play from now` button in the piano mode in the issue.

**Comment by nesbox** [comment]
Added `loop` button, also `play from now` keeps playing after frame is changed cef8925bf4d6ba4920c3e131806730c8273110c4

![image](https://user-images.githubusercontent.com/1101448/158157947-b7d8db52-2f7a-48e7-9c86-578c31d1c090.png)
