### ISSUE TITLE
memcpy glitches out in the web build

### ISSUE THREAD

**Issue by verysoftwares** [nesbox/TIC-80#1875]
i'm using memcpy to move screen memory around. see the glitches here, choose 2-4 players and move around: http://tic80.com/play?cart=2740

![image](https://user-images.githubusercontent.com/54413321/162589926-ad17ebea-5c60-454a-86ca-76acc4278b7a.png)

a downloaded cartridge works just fine.

**Comment by nesbox** [comment]
Just reproduced it on the latest html build and I'm wondering what could be causing it, maybe compiler optimizations?

**Comment by nesbox** [comment]
No, I see the same thing in TIC-80 for desktop, are you sure your code is working correctly?

**Comment by verysoftwares** [comment]
i can't reproduce on desktop (0.90.1723 Pro)

**Comment by nesbox** [comment]
I see glitches on the latest dev build
![image](https://user-images.githubusercontent.com/1101448/162694564-3d012878-98bb-484e-b705-7e559b61cf10.png)

**Comment by mbikovitsky** [comment]
AFAICT, there are two related issues here:

1. The LUALA code uses `memcpy` to copy potentially overlapping buffers.
2. The TIC-80 `memcpy` implementation [uses the C `memcpy` function](https://github.com/nesbox/TIC-80/blob/e1dbcd001c7333b9b196ab9c04dffabc963f5c08/src/core/core.c#L129) to do the copy.

It is undefined behaviour to use `memcpy` on overlapping buffers: <https://en.cppreference.com/w/c/string/byte/memcpy>. But, [the documentation for the TIC-80 `memcpy`](https://github.com/nesbox/TIC-80/wiki/memcpy) doesn't specify this as a constraint, so users have no way to know of this pitfall.

The immediate workaround for @verysoftwares is to copy memory manually. Something like:

```lua
function memmove(dst, src, length)
    if dst <= src then
        for i=0,length-1 do
            poke(dst+i, peek(src+i))
        end
    else
        for i=length-1,0,-1 do
            poke(dst+i, peek(src+i))
        end
    end
end
```

It's slower, but in my testing the bug is no longer present (AFAICT).

@nesbox, I think the correct fix is to use [`memmove`](https://en.cppreference.com/w/c/string/byte/memmove) in `tic_api_memcpy`, since that's the behaviour of the TIC-80 `memcpy` users expect.
