### ISSUE TITLE
F7 doesn't save what's drawn in OVR

### ISSUE THREAD

**Issue by verysoftwares** [nesbox/TIC-80#1880]
is this intentional?

**Comment by nesbox** [comment]
In short, yes, this is by design, we only have a `240x136x4bpp` buffer to save the cart cover, but the ovr layer has an extra 16 colors.
Theoretically, you can save a screenshot by pressing `F8` and then import it with `import cover cover.png` and all colors will be automatically converted to `4bpp` mode.
