### ISSUE TITLE
Building for Nix results in no GUI

### ISSUE THREAD

**Issue by rschulman** [nesbox/TIC-80#1922]
Hello! I'm working on putting together a derivation (build script, essentially) for Nix. The build is currently completing successfully, but the resulting binary is printing to `stdout`:
```
 TIC-80 tiny computer
 version 1.0.0 ()
 https://tic80.com (C) 2017-1980

 hello! type help for help
>
```
but not creating its own window. In addition, typing anything at the prompt results in no response.

I'm guessing that this is being caused by a missing dependency (at least that makes the most sense to me given the circumstances). Anyone have an idea of what might be missing that would cause behavior like this but which would not break the build itself?

Thanks!

**Comment by nesbox** [comment]
We use SDL2 lib to render UI, I think SDL2 didn't create the window for some reason.

**Comment by joshgoebel** [comment]
@rschulman Any luck on this?

**Comment by 44100hertz** [comment]
I still have this issue.

**Comment by winny-** [comment]
Hello, this issue is an issue with Nix, not with TIC-80.  See my derivation here https://github.com/winny-/nixos-configs/blob/master/package-overrides/tic-80/default.nix

The root cause was due to how Nix handles libraries, and there are documented work arounds in the SDL2 derivation.

This ticket should have been created as a discussion in the Nix Discourse or nixpkgs github repository as it is an issue specific to Nix and packaging Tic-80 on nix.
