### ISSUE TITLE
alternate dofile() behavior

### ISSUE THREAD

**Issue by ambyra** [nesbox/TIC-80#203]
dofile("file.lua") should look for file.lua in the same directory as the .tic game file. Also, I don't like that TIC80 creates a new game folder for each version release. These two issues make it hard to use version control software, like GIT, to save progress.

**Comment by DDevil97** [comment]
Someone? Having the same problem??

**Comment by nesbox** [comment]
it loads `file.lua` from the working directory
you could keep .tic and .lua files in the same directory and run TIC from it

as for new directory for each folder, going to stop do it when API and Cart layout will be more less stable

**Comment by to90zeroblue** [comment]
On OSX, dofile("filename.lua")  returns a "file not found" error. I have to enter the full directory name. This is why I've been keeping the .lua file in a separate folder. I'll check to make sure the behavior is different in windows.

**Comment by nesbox** [comment]
yes, because 'filename.lua' not your working dir

**Comment by DjPale** [comment]
I think the idea of including code externally is great 👍  In my limited (pico-8) experience, other in-engine editors are quite OK - but the exception is the code editor. My eyes start to bleed and my head hearts after a short while, and wihle I see that TIC-80 has a great addition of a function-outline - editing code with a real editor (like VSCode) helps so much when you're starting to have more than 200 lines.

So `dofile` is good - it also eliminates the danger of overwriting data when you're working in parallell with code and in-engine editors and accidentaly forget to save/reload properly each time you switch programs

 It only needs to work a bit better with removing the need for tic-80 being launched from your working dir. I usually create a symlink to my dropbox dir in order to share carts on different computers. They become something like `cartdir\dropbox`. In Windows I have to:
* Add tic-80 dir to PATH (once, unless this dir changes with versions)
* Start a cmd-prompt
* Go to the dropbox-dir
* Start tic
* Once TIC is started - I have to cd to my dropbox again
* Finally load the cart

It's not a huge deal, but improving this would be more intuitive and support this "pattern" which I think people enjoy 😄

**Comment by nesbox** [comment]
#715 duplicate
