### ISSUE TITLE
Running `TIC()` function in itself causes TIC-80 to freeze

### ISSUE THREAD

**Issue by TylerMS887** [nesbox/TIC-80#2051]
Can reproduced by adding `TIC()` inside `TIC()`. TIC-80 freezes. This is because `TIC()` is the game's main function, and the freeze is something to do with stack overflows apparently.

**Comment by Trixciel** [comment]
You're not meant to call TIC(), the game calls it 60 times per second already.

Plus, calling TIC() inside TIC() creates loop which the CPU can't escape, which makes it unable to execute the program.

Try it in python for example ! 

Define a function that :
1) Calls itself
2) Returns stuff

It's gonna overflow because you're calling your function an infinite number of times, check out "Recursion" on Google, you'll learn a thing or two !

**Comment by joshgoebel** [comment]
Correct. This is expected behavior.
