### ISSUE TITLE
GIF Compression

### ISSUE THREAD

**Issue by cxong** [nesbox/TIC-80#2218]
The GIFs that TIC-80 creates are quite big; I can usually achieve 90%+ size savings using ezgif.com optimize.

I'm not sure what optimisations if any are used, but I think a few simple tricks can help greatly reduce size. For example:

- Replace pixels that don't change with transparent pixels
- Don't encode frame if identical from last - increase duration of last frame instead
- Analyse total colours used, and use a limited palette if possible

**Comment by bztsrc** [comment]
> I think a few simple tricks can help greatly reduce size

No, not really.

> Replace pixels that don't change with transparent pixels

Doesn't matter, because transparent pixels are encoded exactly as normal pixels (there's just an index in the header to tell which color is the transparent one).

> Don't encode frame if identical from last - increase duration of last frame instead

Not viable, most gif viewers use the global frame delay value. Very very few gif decoder supports the per frame delay feature. Writing an empty frame is what you can do.

> Analyse total colours used, and use a limited palette if possible

Again, pointless because TIC-80 colors are limited to 16 tops (which gives 48 bytes per frame tops), plus TIC-80 already [saves only the colors that's actually been used](https://github.com/nesbox/TIC-80/blob/main/src/ext/gif.c#L326).

What one can do is, keep a copy of the screen, and look for different pixels. Then create a list of minimal enclosing rectangles for those changed areas, and only write those rectangles to the frame. Note that blob-detection is a notoriously lot harder problem than you think, especially if it also has to be performant enough for real-time usage.

Here's a not so efficient, but relatively simple implementation of gif optimization: [gifsicle](https://github.com/kohler/gifsicle/blob/master/src/optimize.c) (however you can't use this code in TIC-80 as-is, because the licenses are incompatible). FYI: this is the algorithm that ezgif.com uses.


And here's a proper implementation of gif optimization: [GIMP](https://gitlab.gnome.org/GNOME/gimp/-/blob/master/plug-ins/common/animation-optimize.c) (this is considerably bigger, lot more complex and harder to read source, and again, license incompatible with TIC-80. But maybe helps to get the idea what's needed to shrink the gif's size).

IMHO: the required complexity to implement this ourselves doesn't worth the effort. Maybe replacing gif.c with another, MIT-license compatible gif library which already has optimization. Not sure which one, maybe [cgif](https://github.com/dloebl/cgif)?

Cheers,
bzt

**Comment by nesbox** [comment]
Also, another GIF encoder https://github.com/martincohen/Punity/blob/master/lib/gifw.h #522

**Comment by bztsrc** [comment]
> Also, another GIF encoder https://github.com/martincohen/Punity/blob/master/lib/gifw.h #522

Pretty neat gif encoder! Unfortunately it does not have any optimization code in it (it just provides `gifw_frame()` which does the low level bit encoding, but leaves the rest to the caller application. You'd still need your own blob detection implementation with this library).

But it's much better written than cgif, I like its coding style. Maybe one could use this gifw lib with combination of a ported [doWidthHeightOptim](https://github.com/dloebl/cgif/blob/main/src/cgif.c#L159) from cgif to achieve small gifs?

If someone replaces gif.c with gifw.h in TIC-80, then I'm willing to contribute the optimization part (sorry, I don't have enough free time to do everything myself).

Cheers,
bzt

**Comment by bztsrc** [comment]
Hi @nesbox,

Look what I've run into by accident: https://github.com/notnullnotvoid/msf_gif

I haven't used it (yet), so I don't know how good it is, but reading the README makes me think it fits the bill perfectly:
- standalone single header library (no deps)
- supports dithering and optimized output (small output)
- seems like its API is straightforward, easy to integrate
- TIC-80 compatible MIT licensing

What do you think? Looks promising I believe.

bzt

**Comment by nesbox** [comment]
I think it looks promising, thanks for the link

**Comment by nesbox** [comment]
I added a new GIF encoder here cff7ee5452524d28e8ec3f98a19a217f156ae6e1
https://github.com/notnullnotvoid/msf_gif
In the example below we see a comparison of two videos with old and new encoders, 10x better on some videos.
![image](https://github.com/nesbox/TIC-80/assets/1101448/3b971633-ac00-4b55-abf8-4cf399ebabae)
@bztsrc thanks for the tip
