### ISSUE TITLE
Is there any limitation when saving cartridge to .png?

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#2311]
### Discussed in https://github.com/nesbox/TIC-80/discussions/2307

<div type='discussions-op-text'>

<sup>Originally posted by **herbix** September 21, 2023</sup>
I'm trying to save a .tic cartridge to .png, which contains ~373KB code and 8 banks of tiles and sprites. tic80.exe crashes when I run `save cart.png`. Does it hit any limitation of png format cartridge?</div>

**Comment by nesbox** [comment]
Crashes on this cart [cart.zip](https://github.com/nesbox/TIC-80/files/12706174/cart.zip)

**Comment by bztsrc** [comment]
Ok, I've debugged this. The reason for the crash is, steganography code reads out of bounds.
```
save cart.png==96356== Invalid read of size 1
==96356==    at 0x2CED34: bitcpy (png.c:217)
==96356==    by 0x2CEF1C: png_encode (png.c:239)
==96356==    by 0x2D5A36: saveCartName (console.c:2468)
==96356==    by 0x2D5C26: onSaveCommandConfirmed (console.c:2514)
...
```
Here's the fix:
```diff
$ git diff png.c 
diff --git a/src/ext/png.c b/src/ext/png.c
index ec07fa94..a2cbd15d 100644
--- a/src/ext/png.c
+++ b/src/ext/png.c
@@ -230,16 +230,19 @@ png_buffer png_encode(png_buffer cover, png_buffer cart)
     const s32 coverSize = png.width * png.height * RGBA_SIZE - HEADER_SIZE;
     Header header = {CLAMP(ceildiv(cartBits, coverSize), 1, BITS_IN_BYTE), cart.size};
 
-    for (s32 i = 0; i < HEADER_SIZE; i++)
-        bitcpy(png.data, i << 3, header.data, i * HEADER_BITS, HEADER_BITS);
+    // only save with steganography if there are enough pixels for the size of the cartidge
+    if (coverSize >= cartBits) {
+        for (s32 i = 0; i < HEADER_SIZE; i++)
+            bitcpy(png.data, i << 3, header.data, i * HEADER_BITS, HEADER_BITS);
 
-    u8* dst = png.data + HEADER_SIZE;
-    s32 end = ceildiv(cartBits, header.bits);
-    for (s32 i = 0; i < end; i++)
-        bitcpy(dst, i << 3, cart.data, i * header.bits, header.bits);
+        u8* dst = png.data + HEADER_SIZE;
+        s32 end = ceildiv(cartBits, header.bits);
+        for (s32 i = 0; i < end; i++)
+            bitcpy(dst, i << 3, cart.data, i * header.bits, header.bits);
 
-    for (s32 i = end; i < coverSize; i++)
-        bitcpy(dst, i << 3, (const u8[]){rand()}, 0, header.bits);
+        for (s32 i = end; i < coverSize; i++)
+            bitcpy(dst, i << 3, (const u8[]){rand()}, 0, header.bits);
+    }
 
     png_buffer out = png_write(png, cart);
```
It looks like multiple changes because of the changed indentation, but actually I have just added `if (coverSize >= cartBits)`, nothing else.

With this fix, if there are not enough pixels to store the cartridge then steganography isn't attempted at all, just the PNG chunk method is used.

For cartridges that fit into the given number of pixels, still both methods (stegano+chunk) are used to provide backward compatibility.

Cheers,
bzt

**Comment by bztsrc** [comment]
Oh, forget to say: I've tested the fix with the given cartridge (562020 bytes) and works as expected. The saved png cartridge is half the size, 272966 bytes (because PNG chunks are compressed). Here is it: 
![cart](https://github.com/nesbox/TIC-80/assets/12779069/feb29b43-4c2b-44b1-9aeb-893d6511c652)

**Comment by nesbox** [comment]
I applied changes from @bztsrc here 324d04d3d1f8ae6655a220690a9e0370bd9862e3
Thanks.
