### ISSUE TITLE
Can't poll player 2 input in ruby cart

### ISSUE THREAD

**Issue by zacx-z** [nesbox/TIC-80#2322]
version:1.1.2736,1.2.2740-dev

In carts written by ruby, `btn` `btnp` always return `false` when the button is above 7.
both gamepads and keyboard (with modified keyboard-gamepad mapping) are not working.
peeking into RAM returns the correct value, however.

I can only reproduce it in ruby carts, which is weird.

**Comment by nesbox** [comment]
fixed here a24f206d61d5f7fa1608a67a5d466972a4bcb397

**Comment by adamico** [comment]
@nesbox mmmh, I think this issue should be reopened because `btn` with no arguments should return a `mrb_fixnum_value` .
This line:
 https://github.com/nesbox/TIC-80/blob/f4578a2f147f69b1cb489fb407de9900d4524578/src/api/mruby.c#L400

Should be similar to:

https://github.com/nesbox/TIC-80/blob/f4578a2f147f69b1cb489fb407de9900d4524578/src/api/mruby.c#L373

(I can work on a PR if you like)
