### ISSUE TITLE
Python scripting issue

### ISSUE THREAD

**Issue by mickeyordog** [nesbox/TIC-80#2348]
Would the developers consider setting the flag to enable importing Box2D in Python? As described on [this page](https://pocketpy.dev/modules/box2d/), it would just involve setting `PK_USE_BOX2D` to 1. It would be quite useful for avoiding some boilerplate collision code for games :)

**Comment by sogaiu** [comment]
I think it was [mentioned elsewhere](https://github.com/nesbox/TIC-80/issues/2339#issuecomment-1784464632) some reasoning about why it might not get enabled.

Didn't hear from nesbox or others though so who knows.

**Comment by TimotheeGreg** [comment]
That has been discussed on the discord too, some people think that would be cool to have it, others think it would make TIC-80 like an other game engine without restrictions.
I agree with this last point, I think TIC-80 should stay restricted with a limited number of libraries to be easy to learn. Other game engines can be used for less restricted projects.

Also in the link sogaiu gave, there's a tip to enable it yourself in your project. However, that would probably not be as easy to share the cart.

**Comment by joshgoebel** [comment]
> However, that would probably not be as easy to share the cart.

If we allowed people to compiled their own HTML runtimes then it'd are pretty easy to build *and* distribute a game (via HTML) using a custom runtime...

**Comment by arcade-mntra** [comment]
@TimotheeGreg 
> some people think that would be cool to have it, others think it would make TIC-80 like an other game engine without restrictions.
> I agree with this last point, I think TIC-80 should stay restricted with a limited number of libraries

The severe restriction of PICO-8 forced me to seek out alternatives and using TIC-80 feels refreshing. 
Infact I found TIC-80 through a python library called Pyxel which takes inspiration from PICO-8 and TIC-80. 
https://github.com/kitao/pyxel

It would still be worthwhile to have the option to enable Box2D for the python version without having to compile from source. 
This has potential to bring massive influx of users to TIC-80 especially from pygame where games are confined to desktops as exporting to web and mobile is a huge pain. 

Python + box2d imo will further open up the Education space since "Learn to program by making Games" is a huge draw with students. 
TIC-80 is a better teaching tool than PICO-8 because of a readable font size, student can write legible descriptive variable names and most schools will choose to teach Python over Lua due to better employment prospects at least in the developing world where I come from.

So obviously I do not agree with above opinion that 

> it would make TIC-80 like an other game engine without restrictions

> TIC-80 should stay restricted with a limited number of libraries

but I will defer to and respect the consensus of the contributors since I don't know what other complications enabling Box2d could cause. Also I am new here and currently don't have the C/C++ programming skills to contribute to code base :P

**Comment by TimotheeGreg** [comment]
I understand your arguments, my opinion isn't really settled and not everyone agrees on the discord either. :shrug:

**Comment by blueloveTH** [comment]
I am glad to enable `box2d` if nesbox agrees with it.

**Comment by nesbox** [comment]
This is a very controversial issue, I personally am against adding third-party libraries, but we can ask the community and decide.

**Comment by arcade-mntra** [comment]
This might be in the gray area, since box2d is part of pocketpy implies it is already added to TIC-80 but is kept disabled due to lack of consensus. 
It could be argued this box2d implementation is not strictly a third-party library but a module inside pocketpy not different than the math or random module.

**Comment by blueloveTH** [comment]
This is not controlled by a runtime bool flag.
With the current setting, `box2d` is hard-disabled which means sources are NOT compiled and cmake won't generate `libbox2d` at all. So there is no magic way to enable it.

**Comment by arcade-mntra** [comment]
Thanks for the clarification. My comment about box2d being already added to TIC-80 is incorrect.

**Comment by bonjorno7** [comment]
If it was added, people could always choose not to use it if they'd rather implement their own physics.

**Comment by TimotheeGreg** [comment]
I guess the problem is to maintain everything up-to-date and running. More we add third-party libraries more difficult it is to maintain.
I am right ? Is that why you are against third-party libraries @nesbox ?

**Comment by sogaiu** [comment]
IIUC, the "limitations" aspect of the system is perceived by some as intentional (cf. "necessity is the mother of invention").  As an example of this being expressed:

> Entirely against the minimal nature and restrictions of the system, just to name one HUGE problem.

from [this comment](https://github.com/nesbox/TIC-80/issues/1991#issuecomment-1193386739).  Hopefully, that quote is a good example (sorry if I misunderstood).

I'm a relative new-comer (and someone who hasn't really made anything with TIC-80) so I can't speak from experience here, but I can relate to the idea of having certain things not being so flexible or extensible [1] tending to lead to one's energies being more concentrated toward the ultimate product / goal...having spent way too much time configuring editors, window managers, etc. (^^;

Having said these things, perhaps it's not always obvious or clear whether a particular addition would be a good "fit" or not...

---

[1] I think the total size of API one has to wrap one's head around is another issue to consider too.
