### ISSUE TITLE
[ Suggestion ] "Download" command to obtain local cartridges in android >10

### ISSUE THREAD

**Issue by duckafire** [nesbox/TIC-80#2517]
I would like to suggest the addition of a new command called: `download <link/code> [name]`. Which would be able to download specific cartridges available at `tic80.com`.

It would be very useful for obtaining cartridges for Android versions, as versions above 10 require a lot of "bureaucracy".

**Example:**
`download http://tic80.com/cart/b88b74e7a6f923251de764d89d6f3507/8_bit_panda.tic panda.tic`

`download b88b74e7a6f923251de764d89d6f3507 panda.tic`

**Comment by Skeptim** [comment]
Note that in version 1.2 you you can set the `autosave` option to `on` in the menu, that will keep carts loaded when using `surf` command.
That might be easier than doing a copy-paste from the website.

Also instead of creating a new command, that could be done from the `surf` command, more or less like was intended in https://github.com/nesbox/TIC-80/pull/1485
