### ISSUE TITLE
Distribute TIC as package in Linux

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#253]
> a Snap package would probably be  the best option, as it can run on most linux distributions that exist
they're also very easy to install

**Comment by tjahneee** [comment]
https://aur.archlinux.org/packages/tic-80/

**Comment by darkhog** [comment]
Please do it also for openSuSE build service so it can be used there. I hear of Shap package for the first time from you, nesbox. I think more traditional approach of rpm for Fedora, openSuSE and Mandriva, then deb for Debian and Debian-like would be in order. Actually you wouldn't even need separate rpms - I've successfully installed rpms meant for Fedora or Mandriva on openSuSE and openSuSE rpms on Mandriva. So I think you'd be safe to just build one rpm to rule them all. Not sure if same can be said for debian-likes, but likely true as well because I've seen people talking about successfully installing packages meant for Debian on Ubuntu and Mint.

**Comment by coreyreichle** [comment]
I don't think snaps would be best, but who am I? :P  Build scripts would be pretty easy to write for debs and rpms.

**Comment by frenetic** [comment]
Even though I agree with @coreyreichle, snap is the "favorite" way of distributing packages for Ubuntu 18.04+.
Also, if TIC80 goes snap, we should also consider going flatpak as well, since it is a more "universal" distribution model.

**Comment by frenetic** [comment]
A case against flatpak: http://flatkill.org/

**Comment by hseiken** [comment]
Security issues are for servers and the paranoid...lol Plus, all it would mean is that someone's not going to download TIC80 because TiC might be the 'evil flatpack' ready to take everyone's data and sell it on the black market despite the fact companies like github are already doing it.

**Comment by Kozova1** [comment]
I made a repo with a working flatpak version of tic80:  
https://github.com/Kozova1/TIC-80-flatpak

**Comment by nesbox** [comment]
@Kozova1 awesome, thank you, I think we can release the flatpak with 0.80

**Comment by farvardin** [comment]
I've looked at the AppImage system as well, as it seems to be less obtrusive than others, you can just launche the executable.

The problem is they describe how to build such a package, but they consider the "make install" should work. On TIC-80, the "make install" seems to be related only to curl and sdl.

I've tried to add the TIC-80 binary into the AppDir and generate the AppImage from there. I got an error but I wonder if it's not something else (" appimage-builder:Tests failed / appimage-builder:Execution failed. Error message: Error while fetching server API version". 

https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html

**Comment by RobLoach** [comment]
If you have [Lutris](https://lutris.net) installed, there's a [TIC-80 Lutris Installer Script](https://lutris.net/games/tic-80/).

Related: https://github.com/nesbox/TIC-80/issues/811

**Comment by Kozova1** [comment]
[https://docs.appimage.org/packaging-guide/hosted-services/opensuse-build-service.html](https://docs.appimage.org/packaging-guide/hosted-services/opensuse-build-service.html)  
Can be used to generate AppImages and other packages perhaps.  
[OBS](https://build.opensuse.org/)

**Comment by nesbox** [comment]
Added `DEB` package generating here a3d4404.
We'll add the other packages support with the next releases.

**Comment by nesbox** [comment]
You can download DEB here to test https://builds.tic80.com/master/2020.09.25/linux

**Comment by Kozova1** [comment]
Since this uses deb packages, it might be possible to use [deb2appimage](https://github.com/simoniz0r/deb2appimage) to generate the appimage.

**Comment by nesbox** [comment]
I did some research on using `appimage/flatpak` containers and I realized we don't need them because TIC-80 already works as a portable app (at least in 0.90-dev) without other dependencies.
For example, `ldd tic80` gives me only these deps
```
# ldd ./tic80
        linux-vdso.so.1 (0x00007fff69d78000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f935fe84000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f935fe7e000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f935fc9c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f935fb4d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f935fb32000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f935f940000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f935feaf000)
```
Please, provide your arguments If you don't agree because I'm not familiar with appimage and maybe I don't see its advantages.
Closing it for now...

**Comment by Kozova1** [comment]
Flatpak's advantage would be using a package manager even on distros which do not use `.deb` packages - you'd only have to write the package once, and then it should run anywhere.

I'm not familiar with AppImages so that'd be something to look into as well.

**Comment by christopher-kleine** [comment]
Okay, here a short overview:
- Flatpak: Got a Manager. Hardly a default installation on any Distro.
- Snap: Got a Manager. Default on Ubuntu. Hardly anywhere else.
- deb / rpm: Manager available (changing the config of those managers required), but can be installed on their respective Distro. Deb is Default on Debian and Debian Based Distros, rpm on Fedora etc.
- AppImage: No real Manager available aside of their Homepage, Installation is not required (Simply download the AppImage, make executable and done). Available on almost all Distros by default. Note: There is a Daemon that lists all AppImages in the Application Menu of the Distro.

**Comment by Kozova1** [comment]
correction: EndlessOS, Fedora, Linux Mint, Centos 7, elementaryOS, PureOS (Mobile linux), and Zorin OS have flatpak by default (according to the flatpak website).

Also consider that snap can be quite slow on non-ubuntu distros.

**Comment by christopher-kleine** [comment]
My bad. But that basically means: Debian (EndlessOS, PureOS), RHEL (Fedora, Centos 7), Ubuntu (Linux Mint, elementaryOS, Zorin OS).

Funny enough: Their base Distro doesn't have Flatpak installed by default. However, it can be installed on a lot of Distros, including Arch Linux and Gentoo Linux.

The same goes for the other solutions. They can be installed on most Distros. But as far as I know AppImage "just works(TM)".

**Comment by Kozova1** [comment]
AppImages have 2 main disadvantages:
1. No sandboxing, so less security - especially important IMO for TIC-80 as it allows code execution.
2. No package manager, so handling updates is a bit of a pain.
Their advantage is indeed their portability.  
Also, flatpak seems to have nicer tooling for creating packages - Flatpak has `flatpak-builder`. AppImages have `appimage-builder` but afaik it only works on Debian-based systems at the moment.

**Comment by christopher-kleine** [comment]
I think that makes it 3 disadvantages. And I agree with the first 2: No Sandboxing and missing a manager are indeed drawbacks. But the build-process shouldn't realy be important. There are CI/CD solutions for that.
And that only Debian based Distros are supported for the builder is - in a way - a good joke from the devs. Or maybe it's been to long since I tried it myself. The last I remember they recommended CentOS 7 since that was their minimum. No other Distro was supported.

And that the builder is build that way is because the AppImage includes only libs that may not be on the client Distro. So they take an older Distro and assume, you have all the common libs. Libs for OpenGL i.e. get packaged along with your AppImage.

And I'm in no way saying we should use AppImage. In fact, I think the perfect solution is not yet out there. Maybe flatpak is the closest we can get to a unified system. Especially since elementaryOS's Shop is based on Flatpak.

**Comment by kevinsmia1939** [comment]
TIC-80 now available on Flathub.
https://flathub.org/apps/details/com.tic80.TIC_80

**Comment by Yamavu** [comment]
I tinkered a little bit and tried creating an appimage from the generic zip (v1.1-pro in my case). It might not work on all systems.
it downloads appimagetool and uses cat, wget and imagemagick v6 or v7. 

I didn't know where to put this and I'm sure it could be more fleshed out but for a simple install it should be good.

```bash
#!/bin/bash

unzip tic80-v1.1-linux-pro.zip

# inflating: tic80

mkdir -p Tic80.AppDir/usr/bin
mkdir -p Tic80.AppDir/usr/share/metainfo

mv tic80 Tic80.AppDir/usr/bin/

ln -s usr/bin/tic80 Tic80.AppDir/AppRun

# get icon 256x256 in Tic80.AppDir/tic80.png
wget https://user-images.githubusercontent.com/13716824/93653165-a3560b00-fa0f-11ea-880b-550c7184ecbc.png
magick 93653165-a3560b00-fa0f-11ea-880b-550c7184ecbc.png -resize 256x256\! Tic80.AppDir/tic80.png
# convert 93653165-a3560b00-fa0f-11ea-880b-550c7184ecbc.png -resize 256x256\! Tic80.AppDir/tic80.png

chmod +x Tic80.AppDir/usr/bin/tic80
chmod +x Tic80.AppDir/AppRun

cat > Tic80.AppDir/Tic80.desktop <<EOL
[Desktop Entry]
Name=Tic80
Exec=tic80
Icon=tic80
Type=Application
Categories=Game;
Comment=TIC-80 is a FREE and OPEN SOURCE fantasy computer for making, playing and sharing tiny games
EOL

cat > Tic80.AppDir/usr/share/metainfo/com.tic80.appdata.xml <<EOL
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>com.tic80.desktop</id>
  <name>Tic-80</name>
  <summary>TIC-80 is a FREE and OPEN SOURCE fantasy computer for making, playing and sharing tiny games</summary>
  <description>
    <p>Tic-80 is a fantasy console for creating, sharing and playing small games and programs. It features a custom code editor, sprite editor, map editor, sound editor and more.</p>
  </description>
  <developer_name>Nesbox</developer_name>
  <launchable type="desktop-id">Tic80.desktop</launchable>
  <icon type="stock">tic80</icon>
  <url type="homepage">https://tic80.com/</url>
  <url type="homepage">https://github.com/nesbox/TIC-80</url>
  <provides>
    <binary>tic80</binary>
  </provides>
  <categories>
    <category>Game</category>
    <category>Development</category>
  </categories>
  <metadata_license>MIT</metadata_license>
  <content_rating type="oars-1.1" />
</component>
EOL

# download appimagetool
wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x ./appimagetool-x86_64.AppImage

ARCH=x86_64
./appimagetool-x86_64.AppImage Tic80.AppDir/ Tic80-v1.1-pro-x86_64.AppImage
```
