### ISSUE TITLE
In what environment does the function MENU work?

### ISSUE THREAD

**Issue by duckafire** [nesbox/TIC-80#2624]
Apparently, the API function [`MENU`](https://github.com/nesbox/wiki/MENU) behavior is different if compared between versions [`1.0.2164`](https://github.com/nesbox/TIC-80/releases/tag/v1.0.2164) and [`1.1.2837`](https://github.com/nesbox/TIC-80/releases/tag/v1.1.2837).

Based on my tests, this function cannot change values in the *"main environment"*, as shown by the GIFs below:

#### 1.0.2164
![MENU-1 0 2164](https://github.com/nesbox/TIC-80/assets/155199080/d6505b4a-71e7-4bfb-ad9b-7345edf51398)

#### 1.1.2837
![MENU-1 1 2837](https://github.com/nesbox/TIC-80/assets/155199080/d61de28a-28e6-416c-8566-b544ea214528)

<br>

**What I would like to know is:**
How should I structure it to work in all versions after   *"beta"* `(>=1.0)`?

<br>

#### Code
``` lua
-- title: bug
-- script: lua
-- menu: 1.-.----

local v = 1

function MENU(i)
    v = 2
    trace(v, 2)
end

function TIC()
    trace(v, 4)
    exit()
end
```

**Comment by Miguel-hrvs** [comment]
Is this your expected output?: 

https://github.com/nesbox/TIC-80/assets/81558772/b03620d4-9293-4abf-bc87-7829ac56744d

**Comment by duckafire** [comment]
> What's the expected output?
> Dev version output: 
> 
> https://github.com/nesbox/TIC-80/assets/81558772/b03620d4-9293-4abf-bc87-7829ac56744d
> 
> 

The output expected is the second (`1.1.2387`), because it can to change/manipule values present in the cartridge code (like variable `v`).

Based in the order of outputs, the value printed in `TIC` was should be equal the value printed in `MENU`.

**Like in your video.**

**Comment by Weeppiko** [comment]
This looks more like an issue with how it decides to resume/restart the cart rather than a MENU issue, considering you're exiting the cart it might have accidentally resuming and running menu in wrong order in that older version. As for how you should structure it, well you don't need to, this might be just an edge case since enter the game menu after exiting the game is not something a person would do normally while playing it.
