### ISSUE TITLE
Switching to fullscreen

### ISSUE THREAD

**Issue by jahodfra** [nesbox/TIC-80#407]
When I press F11 the TIC continuously switches between fullscreen and windowed mode. The transition should happen only once per key down event.

**Comment by nitrofurano** [comment]
and i want to know how to start it in fullscreen, from command line, from configuration, etc.

**Comment by jahodfra** [comment]
https://github.com/nesbox/TIC-80/wiki#command-line-arguments
You can use -fullscreen command line argument to start in fullscreen.

**Comment by nitrofurano** [comment]
thanks! :)

**Comment by nitrofurano** [comment]
i think i found an interesting (and annoying) bug on -fullscreen argument, quite weird behaviour there - when i enter "pic80 -fullscreen cart_1_PaletteDemo.tic" or "pic80 cart_1_PaletteDemo.tic -fullscreen" (from terminal, pic80 installed at /usr/bin/, and from the directory where cart_1_PaletteDemo.tic is), it doesn’t open and run Palette Demo as "pic80 cart_1_PaletteDemo.tic" does - instead of running Palette Demo, it runs nothing, and runs "game title" demo instead when we enter "run"

**Comment by jahodfra** [comment]
@nitrofurano please create own issue on this, because this is not related to the current one. Maybe you can extend issue #432.

**Comment by nitrofurano** [comment]
@jahodfra  i commented there right now, thanks!

**Comment by nesbox** [comment]
fixed keypress repeating
as for _command line issue_ it was fixed here #416

**Comment by jahodfra** [comment]
Thanks, this was really irritating.
