### ISSUE TITLE
Possible issue with sfx: Bass tones sounds high

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#438]
https://itch.io/t/168748/possible-issue-with-sfx-bass-tones-sounds-high
> Hi. I've started to play with Tic-80 and one thing I've noticed as playing with the sfx is that from octave 1 to 3 appears to be a faint sound with higher frequency.

> I tested on phone and on my pc. in both the program showed the faint high pitch. I've tested with all the default wave forms. After, I've tested with a youtube video (something like 25 to 100 hz) to make sure if the problem is not with my speakers. 

> Not sure if it is actually an issue or if it is just the way the dev wants.

**Comment by fangzhangmnm** [comment]
Yeah, I've met the same problem. I think it is because the waveform length is longer than atom length, So the sudden change of waveform will make an square-wave-like sound.

**Comment by hseiken** [comment]
Low pitch + alias will create strange tones.  You can also get strange 'noise' by playing high pitches super high: sometimes good for interesting sound effects, both things are, but the problem is that they're unpredictable and come from different clock speeds and frequencies clashing...therefore it's unknown exactly how they will sound.  However, if you are okay with the randomness, they can be good go-tos for interesting noisy things.  That is, if I am to understand the issue...As well, if you make a waveform that is duplicated twice, that changes octave up by one.  If your wave form is stretched out, it should be the 'normal' sound.  This is also dependent on the frequency range that TIC 80 supports for it's waveforms as well, a real hardware limitation brought into fantasy console land, thankfully.  Work with limitations and you'll learn to search them out and abuse them rather than fear them.

**Comment by nesbox** [comment]
now bass tones sound how they should -1 octave
done
