### ISSUE TITLE
key/keyp: some key presses are not detected if other keys are pressed

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#490]
Run key_demo.tic.txt
1. Press and hold 'p'
1. While holding 'p', press and hold '['
2. While holding 'p' and '[', type 'q','w','e','r','t','y','u','i'.'o'.

Expected result: "p[qwertyuio" is printed.
Actual result: "p[qetyo" is printed. There is no way to type some letters while 'p'+'[' are pressed & held.

I tested it with this cart - [key_demo.tic.txt](https://github.com/nesbox/TIC-80/files/1593828/key_demo.tic.txt)

**Comment by hseiken** [comment]
I believe this is a hardware problem, a design fault that has resided in computers since the standard keyboard interrupt was established.  The keyboard was not intended as a device to accept every button at any given time and the interface was established when bits were scarce.  

There's more details to it than I can provide, but the oldskooler in me is pretty sure that this will hold true in most programs that use running scancodes to pick up keyspresses.  Could be wrong..but this sounds like normal keyboard behavior you describe, to me.

**Comment by nesbox** [comment]
yes, agreed with @hseiken, it's a hardware problem
try to hold `p` and `[` and type `w` in any text editor you want and you won't see `w`

**Comment by lolbot-iichan** [comment]
Holy crap! It really IS a hardware problem. Sorry for bothering.

**Comment by lolbot-iichan** [comment]
@hseiken Thanks for brilliant explanation.

**Comment by hseiken** [comment]
It's not a mega technical explanation, I don't know enough on that side to give you the chin-stroking explanation, but I hope you notice the BS of major computer companies right now which is shown through the irony of your dilemma: a piece of software written in 2017 meant to appear like a computer made in the 80s has a limitation forced on it by modern hardware which hasn't been fixed since the 80s. 

Go figure.

**Comment by frenetic** [comment]
It is a hardware limitation.
Most keyboards can deal with 2 or 3 keys pressed at the same time (like `crtl` + `alt` + `del`).
Depending on your keyboard and operating system, if you try to press 4 keys at the same time, you can hear a beep for error (like pressing `q` + `w` + `e` + `r`).
This beep happens because the keyboard sent a weird signal to your computer.

The so called "gaming keyboards" (mechanical keyboards), can process multiple keystrokes at the same time.
For instance, this bug does not happen with me.
Im using a mechanical keyboard [Logitech G610](https://www.logitechg.com/en-us/product/g610-orion-brown-keyboard), which can handle 26 key pressed at the same time.

**Comment by hseiken** [comment]
It's nice to know we can spend extra to get what was expected with all keyboards.  :(
