### ISSUE TITLE
Show info if your game has problems with sync

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#497]
draw something like SYNC label in the top right corner
also, should be configurable

**Comment by nesbox** [comment]
added `SYNC` label here 8f3e01a
![image](https://user-images.githubusercontent.com/1101448/34567142-1c5843b4-f172-11e7-8619-1acc136eca96.png)

**Comment by jahodfra** [comment]
I have to say that on my desktop (ubuntu Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz) the sync shows almost all the time. I am wondering where's the problem. The games run fast. Could the message show more detail, like FPS?

**Comment by nesbox** [comment]
@jahodfra what do you have in the config here `SYNC_FRAMES=2 -- missed frames`?

**Comment by jahodfra** [comment]
yes, I haven't changed the default config. In windowed mode I see the label more often. When I switch to full screen it is less often. Even in fullscreen 8bit panda displays it during the play.

**Comment by nesbox** [comment]
@jahodfra try to disable `SDL_RENDERER_PRESENTVSYNC ` here
https://github.com/nesbox/TIC-80/blob/4188b9243299a6690e478fc13a4774048779f7ef/src/studio.c#L2747
Do you see SYNC less often?

**Comment by jahodfra** [comment]
I cannot build on head, because I don't have 3rd party dir on my filesystem.

When I build on dc1aa89fd32fa86f6666c6974b986f3c90b27716 I haven't seen
sync too often. So I am not sure if something changed or my computer did
less stuff in the background.


út 9. 1. 2018 v 15:33 odesílatel Vadim Grigoruk <notifications@github.com>
napsal:
