### ISSUE TITLE
SYNC label appears everywhere if your computer is slow

### ISSUE THREAD

**Issue by frenetic** [nesbox/TIC-80#511]
I was running some CPU intensive process on my PC when I decided to play around with TIC-80.

The  `SYNC` label keeps blinking on my screen (even on console...).
Im not sure if `SYNC` should only appear when running a cart or if it is the desired behavior.

**Comment by hseiken** [comment]
The sync lets you know if creating and displaying a frame matches with vsync of the monitor.  AFAIK, it's for debugging internal display mechanics.  I'm unaware of any code that will turn it off at the moment, but it's not intended for public consumption and my guess is it will disappear soon since the software is currently actively developed.

**Comment by Luraktinus** [comment]
![screenshot_20180121-114037](https://user-images.githubusercontent.com/33608674/35193235-0c9df28a-fea0-11e7-96db-830b064c50e0.png)
on a recent Android device too

the SYNC label is annoying and useless because its ALWAYS there, not even while playing a game

**Comment by nesbox** [comment]
ok, agreed, it's for developing/profiling only
added `SHOW_SYNC` variable to the _Config_ (=false by default)
6075159

**Comment by briangordon** [comment]
Any estimates for when this is going to be merged into stable? :)

**Comment by frenetic** [comment]
It is marked as `0.70.0` milestone.
So, probably, when all milestone items are concluded: https://github.com/nesbox/TIC-80/milestone/23

**Comment by nesbox** [comment]
@briangordon don't know, I temporarily have to work on another project and don't have time to finally release .70
