### ISSUE TITLE
Add custom commands

### ISSUE THREAD

**Issue by Tau5** [nesbox/TIC-80#535]
My idea is that you can add on your cartridge metadata something like:
`//commands: [{"name":play,"commands":["load test.tic","run"]}]` (On JSON)
and when you are on the directory where `test.tic` is located and you type on the console `play` it runs `load test.tic` and after `run`

**Comment by jahodfra** [comment]
What is meant by own cartridge? The configuration cartridge?
Otherwise it seems that TIC would have to read through all files in a directory just to parse commands. Also it can happen that command names from different file can be in conflict.

I also don't see how the example benefits the player, isn't possible just to start the cartridge from command line with:
./tic80 load_test.tic ?

**Comment by Tau5** [comment]
For the player it can be dificult to type that commands, its more simple to use only one command for the player

**Comment by jahodfra** [comment]
I think players should be able to directly start the game and not be bothered with writing anything. In browser that's already happening and for other platforms it is not hard to enclose bash script which does the same. So only exception is currently android, which should probably start into "surf" mode.

**Comment by nesbox** [comment]
wontfix
