### ISSUE TITLE
mouse() returns x,y outside 0,0~239,135 when mouse pointer is on screen border

### ISSUE THREAD

**Issue by lolbot-iichan** [nesbox/TIC-80#559]
TEST CASE 1 (bf):
1. run http://lolbot-iichan.github.io/TIC-80/bin/html/bf_mouse2.html
2. move mouse pointer from game screen center to the left
EXPECTED RESULT: x goes down to 0 and stops
ACTUAL RESULT: x goes 5,4,3,2,1,0,255,254,253,252,251,250,249,248

TEST CASE 2 (lua):
1. build and run web version of TIC-80
2. type "new lua"
3. insert "trace(mouse())" line to main TIC function
4. move mouse pointer from game screen center to the left
5. press ESC and read traces
EXPECTED RESULT: x goes down to 0 and stops
ACTUAL RESULT: x goes 5,4,3,2,1,0,255,254,253,252,251,250,249,248

Compare with https://tic.computer/play?cart=24

**Comment by AnastasiaDunbar** [comment]
When cursor goes further into the border's top left corner, `mouse()`'s first two elements will return 255.
To get around this you have to do this:
```js
var m=mouse();
if(m[0]===255){m[0]=0;}
if(m[1]===255){m[1]=0;}
```

**Comment by AnastasiaDunbar** [comment]
![a](https://user-images.githubusercontent.com/11806048/44622921-d9714100-a8c2-11e8-8aec-22958c16e971.gif)

**Comment by nesbox** [comment]
Fixed here 8fab61c
We save in ram mouse pos of full `255x144` screen with border, while `mouse()` API returns pos of `240x136` screen.
![mouse](https://user-images.githubusercontent.com/1101448/97574543-6f9dd600-19fc-11eb-8b67-ca25cd49c54c.gif)

**Comment by nalquas** [comment]
It seems like TIC-80 doesn't adjust for changes in border size due to window resizing, so this issue can still (kind of) appear when the window has been resized (or put in fullscreen).

### Description
- When the TIC-80 window is in its original size, moving the mouse towards the left edge of the window results in `mouse()` returning an x value of ...,3,2,1,0 (which is correct behaviour).
- When the TIC-80 window is scaled (e.g. by extending the window to the right or by going into fullscreen), moving the mouse towards the left edge of the window results in `mouse()` returning x values of ...,3,2,1,0,255,254,... (which is incorrect behaviour)

When compared to the original bug description, `mouse()` now doesn't wrap at the edge of the `240x136` screen anymore, but it does still wrap somewhere inside the border area if the window has been scaled.

### Expected correct behaviour
I would expect `mouse()` to return negative values when going towards the left or top and values >255 when going towards the right/bottom.
This would, of cause, break the RAM layout as more than 1 byte would be required. In that case, clipping the mouse() x/y value to 0-255 would be a good alternative.

### Reproduction
Run the following test script and move your mouse towards the edges of the window (first in its original size, then in scaled/fullscreen). Observe the `mouse()` values wrapping around.
```lua
-- title:  mouse border issue
-- author: nalquas
-- desc:   mouse border issue reproduction
-- script: lua

function TIC()
	cls(8)
	
	-- Get mouse data
	mx,my = mouse()
	bx = peek(0x0FF84)
	by = peek(0x0FF85)
	
	-- Print data
	print("mouse(): " .. mx .. " " .. my, 32, 32)
	text = ""
	if mx < 120 then
	 text = "=> left"
	else
	 text = "=> right"
	end
	print(text, 32, 40)
	print("RAM: " .. bx .. " " .. by, 32, 48)
end
```

### Version
I built TIC-80 from source using the AUR. I'm currently at version `0.90.1501-dev Pro` (this should be commit 29df578db06ab1664923bdbb3af984e513d9942d ) and running this on Manjaro.

**Comment by nesbox** [comment]
We have all these problems because we only have 2 bytes to store mouse XY coordinates.
https://github.com/nesbox/TIC-80/blob/acddaaad3ae5f5f403db9f1a69872697fb49efb5/include/tic80.h#L100

**Comment by nalquas** [comment]
You could workaround the `u8` range limitation by clipping the mouse x/y values to 0-255 before writing them into ram. I'm working on it in my own fork right now, I'll send a pull request when I'm done.
