### ISSUE TITLE
Unable to access the game menu

### ISSUE THREAD

**Issue by abcq2** [nesbox/TIC-80#584]
Hi, I can't edit my key bindings because I can't get to the "GAME MENU".
There is no command for game menu and no instructions.
The changelog says that the game menu is accessed by pressing ESC, but that closes the game.
How do I edit my key bindings?

**Comment by StinkerB06** [comment]
Just load up any [tic.computer/play](https://tic.computer/play) cart from SURF, press escape, and "GAMEPAD CONFIG" should be listed in the menu.

Also note that previous versions had a console command for editing the key bindings. It was taken down just because they had since added in the GAME MENU. This caused the 0.60.3 release to ruin some people's ideas about editing the bindings before starting their actual game.

It should be a great idea that the menu should show up on local carts as well. (Or at least it does if you let TIC-80 auto-boot to your cartridge.)
