### ISSUE TITLE
Investigate memory leak on Linux

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#587]
User said:

> Anyone else noticing a really bad memory leak with the linux version of the tic-80?(edited)
I keep having to restart every couple 5/10 minutes because of how much memory it starts taking up

**Comment by jahodfra** [comment]
I noticed that LUA needs periodical call to collectgarbage, otherwise browser and desktop tic-80 is getting stuck after a while (I allocate quite lot of global memory in my cartridge).

Maybe this is related.

**Comment by metiscus** [comment]
I just cloned, built and ran 7606c2dcc44cc54565ed89ecad9aa2ca2ca96a90 on a linux machine and I have not found any issues running the built-in demo carts and the mainfighter cart downloaded from the website. I checked for issues with valgrind and despite running the games for several tens of minutes the memory usage was reasonably stable.
Could you attach your cart to the issue for further debugging?

**Comment by jahodfra** [comment]
I was not the original reporter, but you can crash cartridge by TIC-80 if you run https://tic.computer/play?cart=487 (remove the collectgarbage function and change time of year approximately 20 times).

**Comment by theonlyames** [comment]
It was actually me who asked this on discord. (Didn't expect to see it up on here.) I've been running into these memory issues and crashing while using the editor functions, not any specific cart.

**Comment by HyperHamster** [comment]
Confirmed for: `0.70.6`, `0.80.0-dev`
Linux Distribution: `Arch Linux`

I'm experiencing a similar progressive leak that eventually causes TIC-80 to become unusable without a restart. I can't be absolutely sure that the leak I'm experiencing is exactly the same due to lack of detail in the original report.

What I've discovered is that while the leak is certainly being caused by TIC-80, it isn't being attributed to the `tic80` process, but to the `Xorg` process instead. The program `xrestop` can be used to observe a constant uptick of ~3 kB/s in TIC-80's total memory usage within `Xorg`. From what I understand graphical memory usage is not attributed to the process allocating it, but to the `Xorg` process instead, and therefore the leak is likely being caused by graphical memory that is being constantly allocated somewhere without being freed.

**Comment by michaeldel** [comment]
Bumping the issue to tell the problem remains present on `0.70.6`, on Archlinux as well. Kernel `5.5.5-arch1-1` and `xorg-server 1.20.7-1` ([`xf86-video-intel`](https://www.archlinux.org/packages/extra/x86_64/xf86-video-intel/) video driver). As described above, the `Xorg` process (`/usr/lib/Xorg`) uses more and more memory when running TIC80, up to gigabytes of RAM (5 to 10 times the usual mem usage on my system). No other software seems to cause this.
