### ISSUE TITLE
Prevent people from reuploading other people work

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#616]
Hi, i noticed that sometimes people take other authors cartridge, make minimal changes and reupload to the tic "store", sometimes without asking and even changing the author.
Now it just happened to me, somebody took [my game](https://tic.computer/play?cart=548) and [reuploaded](https://tic.computer/play?cart=553) without asking permission (without changes it seems).

Now, it's a free game and nothing really spectacular, but i'd prefer this wouldn't happen. 
I don't know how it could be done, but perhaps a "report" button would be enought for the moment. Maybe in future there could be some kind of guidelines or some minimal review

**Comment by SergioFLS** [comment]
and add the terms of service, too?

**Comment by StinkerB06** [comment]
I'm sorry that M4jestik re-upped your cartridge. I have no frickin' clue as to why he would do that when your game already exists on the TIC-80 site. What has he been doing in the official Discord?

**Comment by frenetic** [comment]
I agree and disagree.

Some people are using fantasy consoles, such as TIC80, to learn about game development.
Reading other people's code, understanding what they did and performing small tweaks is one of the many ways people learn game development (and programming in general).
By stating that, a "report" button, when used in a bad manner, may disencourage people to follow this learning path.

I do agree creators of games of source code deserves their credit, and for the scenario Im talking about, people should be encouraged to give credit, and to thank, the original creators for their game.

Finally, Im in favor of a `report` button. If, and only if, we have a tool and/or a community guideline to enable people who are learning by modifying to give credit to the original developer.

**Comment by msx80** [comment]
> Some people are using fantasy consoles, such as TIC80, to learn about game development.
Reading other people's code, understanding what they did and performing small tweaks is one of the many ways people learn game development (and programming in general).

You're totally right on this and i recognize the learning potential of fantasy consoles, but notice that reuploading your "experiments" is totally unnecessary for the learning experience you just described. Perhaps asking permission, at least doing some minimal changes, would be the minimal requirements for reupload, but often neither of them are done

**Comment by frenetic** [comment]
I think, sometimes, people reupload their modified versions so they can share with friends or study groups.
I know Im just looking to the bright side here...
Guidelines or tools to help these learners to point to the cartridge they "forked" would be, in my opinion, the first thing we should implement, before implementing the `report` button.
This would help to improve our community. Would help people who are learning to say `thanks` to the people they are learning from.
This would also teach them about ethics (and people DO need to learn a thing or two about it)

But I totally understand your point of view. We spend hours of our time trying to craft something amazing, and some other random person trying to steal our `glory`...
This kind of people should be banished from the community.

If, @nesbox decides to implement a `report` button, I'd not oppose. Id just warn people to take care where they report things. Sometimes it is easier to talk and solve a small credit mistake than shaming a person for a n00b mistake.

(I know sometimes I really only look to the bright side... But I've been working with dev communities for 10 years now, and I see a lot of young people afraid to participate...)

**Comment by hseiken** [comment]
Ive seen this stuff happen time and time again.  When Visual Pinball was new, there was the issue of mods people would make and reupload, putting their name on a table when all they did was change the ball graphic, or poop around with the physics numbers on one or two objects (usually the flippers).  The way they solved it was to have an option to lock tables.  This pissed off almost everyone since the original author's idea was that since everything is editable and not meant to be 'exported' as a standalone, as noted here, people would learn how to make their own tables by first editing someone else's table.  

The long and short of it is, there were only 3 people getting truly pissed off at this practice and most others didn't care. The practice didn't stop because of locking tables becoming an option.  What ended up happening was the people that were accused of trying to take credit for other's work ended up being ostracized from the community (they're putting their own name on it, so it's not like you didn't know who it was) and therefore the rest of the community almost literally didn't download or play their works, tables stop being locked altogether and they left the scene.  It was quite a bloody battle (in internet terms) that lasted for months, with some people even wanting to take legal action...

And during all of this, the worst offenders of the open source aspect were actually people that were on ebay selling DVDs of everyone else's work in the  community; 1000's of table (including mine) were always going up on eBay where someone else would get paid for making the content that was merely curated by another person.  Several community members were fairly diligent about reporting to eBay this copyright infringement and theft (they were also selling ROMs of real pinball tables as many of the tables were PinMAME recreations that used an emulator running parallel to Visual Pinball, essentially the pinball equivalent to MAME) and eventually that too died out.  The thing was, though, that most of the DVDs didn't sell but 2 or 3 copies.

The point I'm trying to make is that...it was 10x the work to deal with the situation, it split the community itself into pieces since there were arguments about this between the factions of 'modding is okay/modding is not okay/modding is okay but don't distro/modding is never okay even with credit' etc.  and lead the developer of Visual Pinball itself to just quit the project before it was really finalized. Tempers flared up quite easily over this and all because someone was insecure in the fact that their work was good and someone else wanted to put their name on it and thought that this somehow would ruin or steal their reputation for good work.  

It didn't and never did; everyone knew who made the original, even when their name was removed because their styles were unmistakeable.  And the modders didn't make anything from scratch EVER and had no style whatsoever; when there were no tables to rip off from that person anymore, they stopped ripping off. The thing they could never rip off was other people's skills. 

So if you want to go down this road with a locking/don't mod aspect, that's fine, but I've been in multiple communities that have had to deal with this and it's literally a shit show between the most insecure people of the group and everyone else loses as a result; they lose the ability to learn, be invited to code, etc.  Open source is just that.  It's not like it doesn't happen in full-on-not-lua-sandbox-projects either.  Full on open source projects have been stolen outright. 

I will say this:  Music gets pirated, books get plagiarized, movies get re-edited and in the end, the copies are always worse and people know their crap.  What would be worse; no one sharing anything out of fear, or everyone sharing everything because we are human and that's what we do?

If you still feel like locking up your work, I won't argue with you, but experience and history shows this is the wrong way to go and I'm quite positive if I was really diligent on making an argument more than typing as much as I have here, statistics would point out that I'm right; giving a fuck about 1% of people in this way is counter productive and flies in the face of what this project is about.

**Comment by SergioFLS** [comment]
is the TIC-80 website moderated?

**Comment by hseiken** [comment]
Well, the only thing I know for sure is 'automation doesn't work' in this kind of thing. It's just a challenge for people to try and beat the system whether they're interested in plagiarizing or not. Considering source is likely to be available for every cartridge, most people can recognize and point out their own coding patterns...I think this would be useful in identifying members who are going against the good will of another member's sharing...It's a bit like a fingerprint, no one uses the same language quite the same way, programming is personal and so is the nomenclature for even the most obscure of elements in the program. It's a bit like copying a paper for school; if you don't change much, it's obvious it was plagiarized.  

It might be nice if people want to mod other people's games and share those, possibly tag them as modded as an option and have them appear on the original game's upload as a non-image link so that it doesn't 'hijack' the original, but gets to exist, and the owner of that page has the option of excluding mods or encouraging them to do a new page for it if they think it's far enough removed from their work to be a new thing (i.e. more than just tweaking a number or two, but something more akin to a 'total conversion' like you see with commercial engines like Quake that Quake Rally, a racing game built with the Quake engine). 

It must be restated, though; no automation/complaint system will work in this kind of context. Social media has been proving that for almost 2 decades now.

**Comment by frenetic** [comment]
Agreed!
Community identifying possible `hijacks` and mods taking care of such conflicts seems to be the best approach.

**Comment by nesbox** [comment]
Let's add "Report" button and let people assign the origin of a game as part of #923 issue.
