### ISSUE TITLE
TIC-80 makes my Macbook Pro run extremely hot

### ISSUE THREAD

**Issue by jordanranson** [nesbox/TIC-80#631]
I just started playing around with TIC-80 but I can't run it for more than a few minutes on my 2017 MacBook Pro (16gb, i5, Intel Iris HD) without it becoming extremely hot and the fans going crazy. I also notice that the red "SYNC" text pops up almost constantly, even just idling on the "terminal" home screen. I don't think it's my computer either because I can run Sketch, Unity, and PICO-8 without the same issues.

Do you have any advice on how to fix this behaviour or any plans on improving performance?

Thanks!

**Comment by gustavopezzi** [comment]
I had the same issue on my MacBook Pro. A _top_ was showing Tic running on 90%+ CPU. I have no such problem on my Linux machine.

**Comment by hseiken** [comment]
I have seen reports on other programs running the fan hot with huge CPU somehow by how the OS handles checking for interrupts (i.e. listening for keyboard). It could happening because of something like this. I'm not a low level programmer myself, but I have heard it affecting multiple other programs. If I remember any specifically, I can link to those projects for the dev to look into their solutions, assuming this is the issue.

**Comment by carlsmith** [comment]
That's odd. I'm running TIC-80 on a Macbook Air 13 (mid-2013), and everything is butter smooth, without needing the fans at all.

**Comment by nesbox** [comment]
it was fixed in .70
closing

**Comment by gustavopezzi** [comment]
Hi Vadim, what was the commit/PR that fixed this issue?

Thank you.
