### ISSUE TITLE
Keyboard mappings broken!

### ISSUE THREAD

**Issue by voze** [nesbox/TIC-80#655]
The TIC-80 thinks my nordic keyboard is American(or british).
**Really annoying**. I don't have this problem in 0.60

**Comment by yamachan** [comment]
Same situation with Japanese keyboard.
I also don't have this problem in 0.60.3.

**Comment by nesbox** [comment]
yes, we should read keyboard Keycodes instead Scancodes
https://wiki.libsdl.org/SDL_Scancode

**Comment by db0z** [comment]
@nesbox, a replacement will probably not work, because a) games that use key()/keyp() should probably expect a consistent layout (like for WASD and stuff), b) Keycodes are separate for punctuation characters on the same key, like ? / and { [, and they depend on the layout as well, so they can't be mapped to `tic_key`s properly. The only way I see is to keep Scancodes while also using Keycodes for text input separately.

**Comment by nesbox** [comment]
fixed here 607ebd6

**Comment by nesbox** [comment]
fixed here #707
