### ISSUE TITLE
TIC-80 needs more English-language YouTube tutorials/gameplay videos

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#667]
Most of them I found weren't even in English, the speaker-language TIC-80 is. This includes Spanish and Russian, but there's more. I'm American.

So, if anyone discovers this issue, PLEASE upload your _whatever_ thing about TIC-80 in English.

**Comment by AnastasiaDunbar** [comment]
Not really an issue and the [wiki page](https://github.com/nesbox/TIC-80/wiki) exists. But I see you'd probably prefer to watch an audiovisual demonstration instead of reading.

**Comment by StinkerB06** [comment]
It's a serious issue for me, they need to stop. And I even remember uploading a cartridge to the TIC-80 site preceding this issue.

**Comment by nesbox** [comment]
it's not TIC related issue, closing...

**Comment by AnastasiaDunbar** [comment]
To upload a cartridge to TIC-80:

1. Load your cartridge in TIC-80 to add the cover by pressing F7.
2. Go to your [profile](https://tic.computer/profile) by clicking on your username.
3. Scroll down and click on [**Add game...**](https://tic.computer/add).
4. To find the TIC-80 directory, choose file and type `%appdata%\com.nesbox.tic\TIC-80` into the address bar and hit enter.
5. Select category, add description and submit.

**Comment by StinkerB06** [comment]
@AnastasiaDunbar I already know how.
@nesbox I know it's not related to TIC-80's features, but just what's gotten on YouTube. Can you try to promote TIC-80 in the **_exact_** way as Lexaloffle's PICO-8, so that more English people can get the hang of doing such videos?

**Comment by hseiken** [comment]
Pico8 was given away as part of another project that already had traction.  Then a few projects that were already aware of Pico8 approached Zep in using it to partner up with and boost their own projects.  Zep didn't do anything, to my knowledge.  Plus, Pico8's been around for probably 5 years or more at a near finished state.

**Comment by hseiken** [comment]
Also, all of the 'help' that has been created for Pico8 are largely from the community and not Zep himself. I might add 'what's the point of TIC80 if it's just trying to be Pico8?'

**Comment by StinkerB06** [comment]
WHY
https://www.youtube.com/watch?v=Ej1Qg-SOgBA

**Comment by frenetic** [comment]
@hseiken is totally right.
This video can help you all understand Pico8/fantasy-consoles - https://www.youtube.com/watch?v=87jfTIWosBw

Pico8 came first and created a community around it. The concept of a community having fun creating things helped the bloom of more communities, like TIC80 or PixelVision.

**Comment by frenetic** [comment]
I totally understand how upsetting it is when you want to learn something but documentation and tutorials do not exist in your language.
Believe me, that is one of the reasons I had to learn English.

But the thing is, learning English isnt cheap. It takes time and, in most cases, money.

Since not all countries are rich, and not all people can afford, those who know english try their best to include other people.
They try to create a community in their country or, in cases like Spanish, in a multitude of countries (20 countries have Spanish as official language).
They are not trying to exclude the english speakers. But since tools and documentations are written in english, they try their best to focus on people that are left out.

Sometimes, when we want our community to be successful, we have to get our hands dirty. Be the first to write a tutorial or make a video on our language, teaching others how to use the tool/software/game/programming-language we love.

Be the first!
Try something new and document your experiences (articles, videos, wikis). You will learn a lot and a lot of people will learn from you. In the end, the entire community will win.

A small story:

As a developer, and Python User Group member, I had multiple opportunities to teach programming to poor kids/adolescents. Here in Brazil poor kids barely speak our own language, so it will be hard to expect them to know english. Teaching logical thinking and the meaning of simple words, like **if**, **else**, **for**, etc, we could build small programs and get the young ones interest in programming.
Im really happy Python have a brilliant Brazilian community, who translated the entire documentation to Portuguese. Because of that, we could help a lot of kids and adolescents learn how to code.

PS: the link posted here by one of our members is in Brazilian Portuguese (my native language). The text was a Google Translation from english to portuguese, since it contains basic translation errors. Probably the author does not speak english.

**Comment by StinkerB06** [comment]
The user had the Android file browser in English, unless it's the TIC-80 app itself that's making it English, I don't really know. If it's not doing that then, he otherwise might have some English capability.

**Comment by StinkerB06** [comment]
NOT AGAIN! https://www.youtube.com/watch?v=54T-IO1hPoY

**Comment by StinkerB06** [comment]
![image](https://user-images.githubusercontent.com/30059831/51504529-5e8b5400-1d96-11e9-8205-c547824eee67.png)

It just continues and continues...

**Comment by oliverKuha** [comment]
I love how TIC-80 is getting traction around the world! I hope that someday I can do my part by contributing some tutorial or other material for this project... in my mother tongue. Would be nice to be part of the TIC-80 movement.
