### ISSUE TITLE
[linux] sokol build rendering vertically flipped

### ISSUE THREAD

**Issue by thoughton** [nesbox/TIC-80#825]
Hi,

I'm building on Ubuntu 18.04. The "pro" build works fine. However the "pro-sokol" build's rendering is flipped vertically:

![image](https://user-images.githubusercontent.com/38389/55109352-916f0280-50cd-11e9-8799-dadb2f5d610a.png)

Note that I've built and used sokol in my own projects on the same system and have not encountered this issue before.

Thanks!

**Comment by kawa-yoiko** [comment]
Hi! If you are building from `master` then I believe it's caused by #821 which I wasn't able to test on Linux... I guess I shall look deeper into Sokol and find a way to fix and test this soon.

Meanwhile, would you please try changing this line

https://github.com/nesbox/TIC-80/blob/e968db3458b69523801dc016a559dcd0c6aa0803/src/system/sokol_gfx.c#L133

to the following and check whether it works?

```c
.content = verts_flipped,
```

**Comment by thoughton** [comment]
Sorry I didn't get a chance to test the change earlier, but I've just pulled from `master` and can confirm the problem is fixed - thanks a lot!
