### ISSUE TITLE
FIX IT

### ISSUE THREAD

**Issue by MicroshaftCorp** [nesbox/TIC-80#833]
Please.

- I can't upload, always shows too large error

- Almost every cart i download won't load

- This needs a emulator (like.. TICbox?)

**Comment by StinkerB06** [comment]
- What is your OS and system specs? What's the file size of the *.tic file you were trying to upload to the website?
- What are the file sizes of the carts you downloaded? Can you provide which ones that won't load?
- Do you really think a TIC-80 emulator would exist? I don't think so, because the TIC-80 app is like an emulator of a console/computer that never existed.

**Comment by saranvdev** [comment]
>  TIC-80 app is like an emulator of a console/computer that never existed.
I would agree, except there's one small thing - RAM memory isn't limited, for example we can create a 9999999 element array and the app won't crash.
I also don't know if CPU cycles are the same

**Comment by MicroshaftCorp** [comment]
*Windows 10 
*both unsure
*still unsure. Also all but Mario Bros
*Makes sense

**Comment by BuoYancYdabl** [comment]
Okay, there is some tips about github and TIC-80:
Never made title of issue like this. Shortly describe your issue and fully describe it on main note. Thats another reason - i dont understand what you cant upload. Are you uploading cart to tic.computer or you got mess and you meant download? And what the heck about emulator? TIC-80 is fantasy console, that exists on every popular platform, even on linux (if im not wrong). TIC-80 not needed an emulator.

**Comment by carlsmith** [comment]
Yeah, just for clarity, TIC-80 is a *virtual* console, so it is effectively implemented as an emulator, except that the console being emulated only ever exists in emulation. The physical console is imaginary, defined only by its spec.
