### ISSUE TITLE
Implementation of Python

### ISSUE THREAD

**Issue by rahul3125** [nesbox/TIC-80#935]
Please  include Python as programmable language as it's very popular and widely used and can be used for machine learning easily and machine learning , neural networks can be written from scratch in python .

**Comment by nesbox** [comment]
maybe, one day... :)
but, to be honest, we need a library to run python code in the browser in this case

**Comment by ddelemeny** [comment]
https://github.com/micropython/micropython looks like a good candidate for this.

(I'd love to see it happen, but I'm a bit out of my league to make it happen)

**Comment by jminor** [comment]
I made some progress towards embedding micropython. @nesbox, would you be open to accepting a PR which adds python support? I'm fairly confident that I can get it working in the desktop build, and micropython is certainly very portable and much smaller than CPython, but I want to double check before I go further.

**Comment by nesbox** [comment]
Hi, 
Of course, I'm open to the PR :)
A lot of users asked me for Python support, but I wasn't sure I can get it working on all the supported platforms, especially a browser via WASM, it will be awesome if you solve this.
Thank you.

**Comment by nesbox** [comment]
btw, I just found a repo with MicroPython working on WASM https://github.com/rafi16jan/micropython-wasm

**Comment by nesbox** [comment]
@jminor any news? :)
Do we need to add it to the .90 version?

**Comment by jminor** [comment]
I did some preliminary steps just my following the same patterns as the Squirrel and Wren language support. Currently I'm stuck on trying to get micropython to build correctly via cmake. You can see my progress here: https://github.com/nesbox/TIC-80/pull/1237

If anyone is more familiar with cmake than I am, I would appreciate a little assistance. I think maybe getting cmake to execute the micropython Makefile might be a better choice, since the micropython porting setup is quite complex and likely difficult to reproduce in cmake.

**Comment by jminor** [comment]
I made some progress, but it looks like I might need to wait for this micropython PR to land (or at least compile properly) https://github.com/micropython/micropython/pull/5964 since the embedding example in the main branch is currently broken.

I was able to manually build libmicropython from an older version and get TIC-80 to link to it, but there are some missing symbols, so it doesn't work yet.

**Comment by jminor** [comment]
The upstream issue in micropython is resolved and I have Python support partially working in TIC-80. If anyone can help with the remaining work, you can see details here: https://github.com/nesbox/TIC-80/pull/1237

**Comment by koltenpearson** [comment]
In case anyone who would be able to help is watching this issue, I have opened #2184 trying this again with pocketpy as the python backend. 

As pocketpy was designed to be embedded into game engines it should be a lot smoother to make work. The dev already has a [demo](https://pocketpy.dev/static/web/) of it working in browser. 

The one issue is getting c++17 enabled on all platforms, see the PR for details.

**Comment by TimotheeGreg** [comment]
Python has been implemented, this issue can be closed ^^
