### ISSUE TITLE
Sounds not playing in Google Chrome in exported game

### ISSUE THREAD

**Issue by Serious07** [nesbox/TIC-80#972]
Google Chrome version: 78.0.3904.108 64bit
TIC-80 version: 0.70.6

Game source code: https://t.co/Awm6oA7gEz?amp=1
Game url loaded on web server: https://gregtechrus.ru/SpaceInvaders/

Reproduce steps:
1) load Lesson25
2) export
3) upload to server
4) reload web page with game
5) no sounds in game

Error in Google Chrome:
https://imgur.com/UQaslKV

**Comment by stefandevai** [comment]
This happens because Chrome has changed its default behavior with autoplay sounds to avoid sounds playing without the user consent in some websites.

And that's what the warning says, to create an audio context in Chrome you have to do it after a user gesture (user click, touch, button, etc.). That's how it's done in games uploaded to the TIC-80's official website, for example, you have to click on the cover image in order to play the game.

Right now sites in which you can upload your game (like itch.io) add a cover by default, so I'm not sure if adding a default cover on the generated HTML would have an impact on that. What do you think @nesbox ?

As a workaround, you can replace your generated HTML file with [this one](https://github.com/stefandevai/amethyst-waters/blob/gh-pages/index.html).

**Comment by nesbox** [comment]
I think the idea with cover is great, will try to use your workaround.
Thank you :)

**Comment by stefandevai** [comment]
@nesbox, have you started working on this issue? If not, I have some free time right now, I could do it :)

**Comment by nesbox** [comment]
I'm not started :) pls do it if you have time.
As I see you just need to update this file `build/html/embed.html`.
Thank you for your help.
